/**
 * Step 2 of the import pipeline.
 *
 * Reads your reviewed data/import/review.csv and:
 *  - always writes data/generated-listings.ts (so the site can use the real
 *    data immediately, same as data/placeholder-listings.ts today)
 *  - additionally upserts into Postgres via Drizzle, if DATABASE_URL is set
 *    (i.e. once a Supabase project exists — see .env.example)
 *
 * Also merges in data/import/cover-images.csv (slug,coverImageUrl,source) if
 * present, keyed by slug. That file is separate from review.csv because
 * `npm run import:parse` regenerates review.csv from scratch on every run —
 * anything hand-added there would get wiped, so cover photos live in their
 * own persistent file instead.
 *
 * Run: npm run import:load
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { parse } from "csv-parse/sync";
import "dotenv/config";
import { listingSchema } from "../../lib/validation/listing";
import type { Category, Listing } from "../../lib/types";
import { countryNameEn } from "../../lib/countryNames";

const REVIEW_FILE = path.join(process.cwd(), "data", "import", "review.csv");
const COVER_IMAGES_FILE = path.join(process.cwd(), "data", "import", "cover-images.csv");
const OUT_FILE = path.join(process.cwd(), "data", "generated-listings.ts");

interface ReviewRow {
  name: string;
  slug: string;
  categories: string;
  country: string;
  countryCode: string;
  city: string;
  address: string;
  lat: string;
  lng: string;
  indoorOutdoor: string;
  websiteUrl: string;
  phone: string;
  description: string;
  googleMapsUrl: string;
  originalNote: string;
}

function loadCoverImages(): Map<string, string> {
  const bySlug = new Map<string, string>();
  if (!existsSync(COVER_IMAGES_FILE)) return bySlug;

  const content = readFileSync(COVER_IMAGES_FILE, "utf-8");
  const rows = parse(content, { columns: true, skip_empty_lines: true }) as {
    slug: string;
    coverImageUrl: string;
  }[];
  for (const row of rows) {
    if (row.slug && row.coverImageUrl) bySlug.set(row.slug, row.coverImageUrl);
  }
  return bySlug;
}

function toListing(row: ReviewRow, id: string, coverImages: Map<string, string>): Listing | null {
  const categories = row.categories
    .split("|")
    .map((c) => c.trim())
    .filter(Boolean) as Category[];

  const candidate = {
    slug: row.slug,
    name: row.name,
    categories,
    status: "published" as const,
    country: countryNameEn(row.countryCode, row.country),
    countryCode: row.countryCode || "XX",
    city: row.city,
    address: row.address,
    lat: parseFloat(row.lat),
    lng: parseFloat(row.lng),
    websiteUrl: row.websiteUrl || undefined,
    phone: row.phone || undefined,
    description: row.description || undefined,
    coverImageUrl: coverImages.get(row.slug) || undefined,
    googleMapsUrl: row.googleMapsUrl || undefined,
    indoorOutdoor: (row.indoorOutdoor || undefined) as Listing["indoorOutdoor"],
  };

  const result = listingSchema.safeParse(candidate);
  if (!result.success) {
    console.warn(`Skipping "${row.name}": ${result.error.issues.map((i) => i.message).join(", ")}`);
    return null;
  }

  return { id, ...result.data };
}

async function main() {
  if (!existsSync(REVIEW_FILE)) {
    console.log(`${REVIEW_FILE} not found. Run \`npm run import:parse\` first.`);
    return;
  }

  const content = readFileSync(REVIEW_FILE, "utf-8");
  const rows = parse(content, { columns: true, skip_empty_lines: true }) as ReviewRow[];
  const coverImages = loadCoverImages();

  const listings: Listing[] = [];
  rows.forEach((row, index) => {
    const listing = toListing(row, String(index + 1), coverImages);
    if (listing) listings.push(listing);
  });

  const fileContents = `// Generated by data/import/import-to-db.ts — do not edit by hand.
// Re-run \`npm run import:load\` after updating data/import/review.csv.
import type { Listing } from "@/lib/types";

export const generatedListings: Listing[] = ${JSON.stringify(listings, null, 2)};
`;
  writeFileSync(OUT_FILE, fileContents);
  console.log(`Wrote ${listings.length} listings to ${OUT_FILE}`);
  console.log(
    'Point lib/listings.ts at "@/data/generated-listings" (generatedListings) instead of placeholder-listings to go live.'
  );

  if (process.env.DATABASE_URL) {
    const { db } = await import("../../lib/db/client");
    const { listings: listingsTable } = await import("../../lib/db/schema");
    for (const listing of listings) {
      await db
        .insert(listingsTable)
        .values({
          slug: listing.slug,
          name: listing.name,
          categories: listing.categories,
          status: listing.status,
          country: listing.country,
          countryCode: listing.countryCode,
          city: listing.city,
          address: listing.address,
          lat: String(listing.lat),
          lng: String(listing.lng),
          websiteUrl: listing.websiteUrl,
          phone: listing.phone,
          description: listing.description,
          coverImageUrl: listing.coverImageUrl,
          googleMapsUrl: listing.googleMapsUrl,
          indoorOutdoor: listing.indoorOutdoor,
        })
        .onConflictDoNothing({ target: listingsTable.slug });
    }
    console.log(`Upserted ${listings.length} listings into Postgres.`);
  } else {
    console.log("DATABASE_URL not set — skipped the database upsert (generated-listings.ts is still ready to use).");
  }
}

main();
