/**
 * Regenerates data/photo-credits.ts from data/import/cover-images.csv
 * (written by the venue-photo-finder agent; Wikimedia author/license filled
 * in by backfill-image-credits.mjs).
 *
 * Credits live in a generated TS file rather than Postgres, merged onto
 * listings in lib/listings.ts the same way calendar events are — so adding
 * attribution needs no migration. Each credit remembers which image URL it
 * belongs to, and is only attached while the listing still uses that image.
 *
 * Run: npx tsx data/import/sync-photo-credits.ts   (or npm run import:sync-credits)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse } from "csv-parse/sync";

const CSV_FILE = path.join(process.cwd(), "data", "import", "cover-images.csv");
const OUT_FILE = path.join(process.cwd(), "data", "photo-credits.ts");

interface Row {
  slug: string;
  coverImageUrl: string;
  source?: string;
  sourcePageUrl?: string;
  author?: string;
  license?: string;
  licenseUrl?: string;
}

function isHttpUrl(value: string | undefined): value is string {
  if (!value) return false;
  try {
    const u = new URL(value);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

const rows: Row[] = parse(readFileSync(CSV_FILE, "utf-8"), { columns: true, skip_empty_lines: true });

const credits: Record<string, Record<string, string>> = {};
for (const row of rows) {
  if (!row.slug || !isHttpUrl(row.coverImageUrl)) continue;
  // Wikimedia rows point at the Commons file page; other rows' `source` is
  // the page the photo was taken from (venue site, tourism board, ...).
  const sourceUrl = isHttpUrl(row.sourcePageUrl) ? row.sourcePageUrl : isHttpUrl(row.source) ? row.source : undefined;
  const credit: Record<string, string> = { imageUrl: row.coverImageUrl };
  if (row.author?.trim()) credit.author = row.author.trim();
  if (row.license?.trim()) credit.license = row.license.trim();
  if (isHttpUrl(row.licenseUrl)) credit.licenseUrl = row.licenseUrl;
  if (sourceUrl) credit.sourceUrl = sourceUrl;
  credits[row.slug] = credit;
}

const header = `// GENERATED by data/import/sync-photo-credits.ts from data/import/cover-images.csv
// — don't edit by hand; edit the CSV and re-run \`npm run import:sync-credits\`.
import type { PhotoCredit } from "@/lib/types";

export const PHOTO_CREDITS: Record<string, PhotoCredit> = `;

writeFileSync(OUT_FILE, header + JSON.stringify(credits, null, 2) + ";\n");
const licensed = Object.values(credits).filter((c) => c.license).length;
console.log(`Wrote ${Object.keys(credits).length} photo credits (${licensed} with a license) to data/photo-credits.ts`);
