import type { EventSeries } from "@/lib/types";

// Display metadata for race series (data/calendar-events.ts), separate from
// site categories (lib/categoryMeta.ts) — a series is what's racing, a
// category is what kind of venue this directory lists.
export const SERIES_LABEL: Record<EventSeries, string> = {
  f1: "F1",
  f2: "F2",
  f3: "F3",
  f4: "F4",
  motogp: "MotoGP",
  gt3: "GT3",
  gt4: "GT4",
  imsa: "IMSA",
  wec: "WEC",
  wrc: "WRC",
  wrc2: "WRC2",
  wrc_junior: "WRC Junior",
  nascar: "NASCAR",
  indycar: "IndyCar",
  formula_e: "Formula E",
  elms: "ELMS",
  supercars: "Supercars",
  dtm: "DTM",
  btcc: "BTCC",
  tcr_europe: "TCR Europe",
  tcr_world_tour: "TCR World Tour",
  super_gt: "Super GT",
  super_formula: "Super Formula",
  porsche_supercup: "Porsche Supercup",
  wkc: "World Karting",
};

export const SERIES_FULL_NAME: Record<EventSeries, string> = {
  f1: "Formula 1",
  f2: "FIA Formula 2 Championship",
  f3: "FIA Formula 3 Championship",
  f4: "Formula 4",
  motogp: "MotoGP",
  gt3: "GT World Challenge Europe",
  gt4: "GT4 European Series",
  imsa: "IMSA WeatherTech SportsCar Championship",
  wec: "FIA World Endurance Championship",
  wrc: "FIA World Rally Championship",
  wrc2: "FIA WRC2 Championship",
  wrc_junior: "FIA WRC Junior Championship",
  nascar: "NASCAR Cup Series",
  indycar: "NTT INDYCAR Series",
  formula_e: "ABB FIA Formula E World Championship",
  elms: "European Le Mans Series",
  supercars: "Supercars Championship",
  dtm: "Deutsche Tourenwagen Masters",
  btcc: "British Touring Car Championship",
  tcr_europe: "TCR Europe Series",
  tcr_world_tour: "TCR World Tour",
  super_gt: "Super GT (Japan)",
  super_formula: "Super Formula Championship",
  porsche_supercup: "Porsche Mobil 1 Supercup",
  wkc: "FIA Karting World Championship",
};

export const SERIES_BADGE_CLASS: Record<EventSeries, string> = {
  f1: "bg-amber-500/15 text-amber-300",
  f2: "bg-yellow-500/15 text-yellow-300",
  f3: "bg-lime-500/15 text-lime-300",
  f4: "bg-cyan-500/15 text-cyan-300",
  motogp: "bg-orange-500/15 text-orange-300",
  gt3: "bg-red-500/15 text-red-300",
  gt4: "bg-blue-500/15 text-blue-300",
  imsa: "bg-teal-500/15 text-teal-300",
  wec: "bg-purple-500/15 text-purple-300",
  wrc: "bg-green-500/15 text-green-300",
  wrc2: "bg-emerald-500/15 text-emerald-300",
  wrc_junior: "bg-lime-600/15 text-lime-400",
  nascar: "bg-rose-500/15 text-rose-300",
  indycar: "bg-sky-500/15 text-sky-300",
  formula_e: "bg-fuchsia-500/15 text-fuchsia-300",
  elms: "bg-violet-500/15 text-violet-300",
  supercars: "bg-indigo-500/15 text-indigo-300",
  dtm: "bg-stone-500/15 text-stone-300",
  btcc: "bg-blue-600/15 text-blue-400",
  tcr_europe: "bg-orange-600/15 text-orange-400",
  tcr_world_tour: "bg-amber-600/15 text-amber-400",
  super_gt: "bg-red-600/15 text-red-400",
  super_formula: "bg-pink-500/15 text-pink-300",
  porsche_supercup: "bg-zinc-500/15 text-zinc-300",
  wkc: "bg-green-600/15 text-green-400",
};

export const SERIES_ORDER: EventSeries[] = [
  "f1",
  "f2",
  "f3",
  "f4",
  "motogp",
  "gt3",
  "gt4",
  "imsa",
  "wec",
  "wrc",
  "wrc2",
  "wrc_junior",
  "nascar",
  "indycar",
  "formula_e",
  "elms",
  "supercars",
  "dtm",
  "btcc",
  "tcr_europe",
  "tcr_world_tour",
  "super_gt",
  "super_formula",
  "porsche_supercup",
  "wkc",
];
