// Generated by data/import/import-to-db.ts — do not edit by hand.
// Re-run `npm run import:load` after updating data/import/review.csv.
import type { Listing } from "@/lib/types";

export const generatedListings: Listing[] = [
  {
    "id": "1",
    "slug": "jeddah-corniche-circuit",
    "name": "Jeddah Corniche Circuit",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Saudi Arabia",
    "countryCode": "SA",
    "city": "Jeddah",
    "address": "Al-Shatee, Jeddah, Governorate of Jidda, Makkah Region, 23612, Saudi Arabia",
    "lat": 21.632953,
    "lng": 39.10352
  },
  {
    "id": "2",
    "slug": "shanghai-international-circuit",
    "name": "Shanghai International Circuit",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "China",
    "countryCode": "CN",
    "city": "Jiading District",
    "address": "Baiyin Road, 菊园街道, Malu, Jiading District, Shanghai, 201821, China",
    "lat": 31.339979,
    "lng": 121.219598
  },
  {
    "id": "3",
    "slug": "miami-international-autodrome",
    "name": "Miami International Autodrome",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "United States",
    "countryCode": "US",
    "city": "Miami Gardens",
    "address": "Hard Rock Stadium, 347, Don Shula Drive, Lake Lucerne, Miami Gardens, Miami-Dade County, Florida, 33056, United States",
    "lat": 25.957479,
    "lng": -80.237856
  },
  {
    "id": "4",
    "slug": "circuit-de-monaco",
    "name": "Circuit de Monaco",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Monaco",
    "countryCode": "MC",
    "city": "Monaco",
    "address": "Cipriani Monte Carlo, 1, Avenue Princesse Grace, Monte-Carlo, Monaco, 98000, Monaco",
    "lat": 43.741041,
    "lng": 7.4299
  },
  {
    "id": "5",
    "slug": "circuit-de-barcelona-catalunya",
    "name": "Circuit de Barcelona-Catalunya",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Spain",
    "countryCode": "ES",
    "city": "Montmeló",
    "address": "Circuit de Barcelona-Catalunya, BV-5003, Can Tabola, Montmeló, Vallès Oriental, Barcelona, Catalonia, 08170, Spain",
    "lat": 41.570008,
    "lng": 2.25881
  },
  {
    "id": "6",
    "slug": "circuit-gilles-villeneuve",
    "name": "Circuit Gilles Villeneuve",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Canada",
    "countryCode": "CA",
    "city": "Montreal",
    "address": "Circuit Gilles-Villeneuve, Chemin des Floralies, Ville-Marie, Montreal, Urban agglomeration of Montreal, Montreal (administrative region), Quebec, H3C 4W7, Canada",
    "lat": 45.500409,
    "lng": -73.527561
  },
  {
    "id": "8",
    "slug": "circuit-de-spa-francorchamps",
    "name": "Circuit de Spa-Francorchamps",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Belgium",
    "countryCode": "BE",
    "city": "Stavelot",
    "address": "Circuit de Spa-Francorchamps, Tunnel de Ster, Francorchamps, Stavelot, Verviers, Liège, Wallonia, 4970, Belgium",
    "lat": 50.436933,
    "lng": 5.970133
  },
  {
    "id": "9",
    "slug": "circuit-zandvoort",
    "name": "Circuit Zandvoort",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Netherlands",
    "countryCode": "NL",
    "city": "Zandvoort",
    "address": "Racesquare Circuit Zandvoort, Laarwall, Zandvoort, North Holland, Netherlands, 2041 TZ, Netherlands",
    "lat": 52.389471,
    "lng": 4.542885
  },
  {
    "id": "10",
    "slug": "autodromo-nazionale-monza",
    "name": "Autodromo Nazionale Monza",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Monza",
    "address": "Autodromo Nazionale di Monza, 5, Viale Vedano, Parco, Monza, Monza and Brianza, Lombardy, 20900, Italy",
    "lat": 45.619106,
    "lng": 9.282641
  },
  {
    "id": "11",
    "slug": "baku-city-circuit",
    "name": "Baku City Circuit",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Azerbaijan",
    "countryCode": "AZ",
    "city": "Baku",
    "address": "Neftchilar Avenue, Nasimi Raion, Baku, 1010, Azerbaijan",
    "lat": 40.372926,
    "lng": 49.852972
  },
  {
    "id": "12",
    "slug": "marina-bay-street-circuit",
    "name": "Marina Bay Street Circuit",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Singapore",
    "countryCode": "SG",
    "city": "Singapore",
    "address": "Marina Promenade, Marina Centre, Civic District, Downtown Core, Central Region, Singapore, 437435, Singapore",
    "lat": 1.291272,
    "lng": 103.864261
  },
  {
    "id": "13",
    "slug": "circuit-of-the-americas",
    "name": "Circuit of the Americas",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "United States",
    "countryCode": "US",
    "city": "Austin",
    "address": "COTA Short Track, Circuit of the Americas pedestrian path, Austin, Travis County, Texas, 78617, United States",
    "lat": 30.135631,
    "lng": -97.63662
  },
  {
    "id": "14",
    "slug": "autodromo-hermanos-rodriguez",
    "name": "Autodromo Hermanos Rodriguez",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Mexico",
    "countryCode": "MX",
    "city": "Mexico City",
    "address": "Estadio GNP Seguros, Avenida Río Churubusco, Mexico City, Iztacalco, Mexico City, 08400, Mexico",
    "lat": 19.405162,
    "lng": -99.096064
  },
  {
    "id": "15",
    "slug": "autodromo-jose-carlos-pace",
    "name": "Autodromo Jose Carlos Pace",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "Brazil",
    "countryCode": "BR",
    "city": "São Paulo",
    "address": "Autódromo José Carlos Pace, 261, Avenida Senador Teotônio Vilela, Interlagos, São Paulo, Southeast Region, 04801-010, Brazil",
    "lat": -23.701824,
    "lng": -46.696916
  },
  {
    "id": "16",
    "slug": "las-vegas-strip-circuit",
    "name": "Las Vegas Strip Circuit",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "United States",
    "countryCode": "US",
    "city": "Paradise",
    "address": "Las Vegas Strip Circuit, Lana Avenue, Filipino Town, Paradise, Clark County, Nevada, 89109, United States",
    "lat": 36.110943,
    "lng": -115.161766
  },
  {
    "id": "17",
    "slug": "yas-marina-circuit",
    "name": "Yas Marina Circuit",
    "categories": [
      "f1"
    ],
    "status": "published",
    "country": "United Arab Emirates",
    "countryCode": "AE",
    "city": "Abu Dhabi",
    "address": "Main Grandstand, Yas Island, Abu Dhabi, Abu Dhabi Emirate, United Arab Emirates",
    "lat": 24.471847,
    "lng": 54.605802
  },
  {
    "id": "18",
    "slug": "motorcity-karting-arena",
    "name": "Motorcity Karting Arena",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Estonia",
    "countryCode": "EE",
    "city": "Tallinn",
    "address": "eTerminal, 1, Laeva, Sadama, City center, Tallinn, Harju County, 10111, Estonia",
    "lat": 59.441209,
    "lng": 24.757483,
    "websiteUrl": "https://motorcity.ee/"
  },
  {
    "id": "19",
    "slug": "laitse-rallypark-go-kart-track",
    "name": "Laitse RallyPark Go-Kart Track",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Estonia",
    "countryCode": "EE",
    "city": "Saue vald",
    "address": "Rallipargi, 3, Ääsmäe — Haapsalu — Rohuküla, Hingu, Hingu küla, Saue vald, Harju County, 76312, Estonia",
    "lat": 59.17345,
    "lng": 24.366537,
    "websiteUrl": "https://laitserallypark.ee/en/services/karting/",
    "phone": "+372 5669 5819"
  },
  {
    "id": "20",
    "slug": "kartingslv",
    "name": "Kartings.lv",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Latvia",
    "countryCode": "LV",
    "city": "Riga",
    "address": "City Padel, 77 k-1, Gustava Zemgala gatve, Jaunā Teika, Teika, Teikas apkaime, Riga, LV-1039, Latvia",
    "lat": 56.975945,
    "lng": 24.163002,
    "websiteUrl": "https://kartings.lv",
    "phone": "+371 27304104"
  },
  {
    "id": "21",
    "slug": "bikernieku-kartinga-halle",
    "name": "Biķernieku Kartinga Halle",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Latvia",
    "countryCode": "LV",
    "city": "Riga",
    "address": "Biķernieku Kartinga halle, 20, Sergeja Eizenšteina iela, Mežciems, Teikas apkaime, Riga, LV-1079, Latvia",
    "lat": 56.965305,
    "lng": 24.232209,
    "websiteUrl": "https://www.bikerniekuhalle.lv/",
    "phone": "+371 26630333"
  },
  {
    "id": "22",
    "slug": "kartlandas-vilnius",
    "name": "Kartlandas Vilnius",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Lithuania",
    "countryCode": "LT",
    "city": "Vilnius",
    "address": "Norfos vaistinė, 1B, Parodų g., Miškiniai, Lazdynai eldership, Vilnius, Vilnius city municipality, Vilnius County, 04132, Lithuania",
    "lat": 54.673941,
    "lng": 25.22404,
    "websiteUrl": "https://vilnius.kartlandas.lt",
    "phone": "+370 626 33555"
  },
  {
    "id": "23",
    "slug": "nemuno-ziedas-nemunas-ring",
    "name": "Nemuno Žiedas (Nemunas Ring)",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Lithuania",
    "countryCode": "LT",
    "city": "Gaižėnėliai",
    "address": "7, Šlaito g., Gaižėnėliai, Ringaudų seniūnija, Kaunas District Municipality, Kaunas County, 53454, Lithuania",
    "lat": 54.917943,
    "lng": 23.689227,
    "websiteUrl": "https://lscentras.lt"
  },
  {
    "id": "24",
    "slug": "autokomerc-karting-centar",
    "name": "Autokomerc Karting Centar",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Serbia",
    "countryCode": "RS",
    "city": "Surcin Urban Municipality",
    "address": "Аутокомерц центар Аеродром, 84c, Светог Саве, Zemun polje, Radiofar, Surchin, Surcin Urban Municipality, City of Belgrade, Central Serbia, 11271, Serbia",
    "lat": 44.833159,
    "lng": 20.31115,
    "websiteUrl": "https://kart.rs/",
    "phone": "+381 63 325 733"
  },
  {
    "id": "25",
    "slug": "turbomax-karting-center",
    "name": "Turbomax Karting Center",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Serbia",
    "countryCode": "RS",
    "city": "Palilula Urban Municipality",
    "address": "Turbomax karting centar, 81, Панчевачки пут, Reva, Palilula, Palilula Urban Municipality, City of Belgrade, Central Serbia, 11060, Serbia",
    "lat": 44.852382,
    "lng": 20.529519,
    "websiteUrl": "https://turbomax.rs/en/",
    "phone": "064 00 00 153"
  },
  {
    "id": "26",
    "slug": "skaj-kart",
    "name": "Skaj Kart",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "North Macedonia",
    "countryCode": "MK",
    "city": "Volkovo",
    "address": "Улица 93, Volkovo, Municipality of Gjorche Petrov, City of Skopje, 1065, North Macedonia",
    "lat": 42.044201,
    "lng": 21.348461,
    "websiteUrl": "https://skajkart.mk/en/",
    "phone": "+389 75 206 236"
  },
  {
    "id": "27",
    "slug": "sofia-karting-ring",
    "name": "Sofia Karting Ring",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Bulgaria",
    "countryCode": "BG",
    "city": "Sofia",
    "address": "Cinegrand, 214, Ring Road, Moreni club, Simeonovo, Sofia, Vitosha, Stolichna, Sofia-City, 1434, Bulgaria",
    "lat": 42.624257,
    "lng": 23.352767,
    "websiteUrl": "https://www.sofiakarting.com/en/"
  },
  {
    "id": "28",
    "slug": "krasna-polyana-karting",
    "name": "Krasna Polyana Karting",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Bulgaria",
    "countryCode": "BG",
    "city": "Sofia",
    "address": "Krasna polyana, Nikola Mushanov Blvd., Sredets Industrial Zone, Sofia, Krasno selo, Stolichna, Sofia-City, 1330, Bulgaria",
    "lat": 42.691065,
    "lng": 23.278819,
    "websiteUrl": "http://www.karting-bg.com/",
    "phone": "+359 2 920 1447"
  },
  {
    "id": "29",
    "slug": "karting-mondercange",
    "name": "Karting Mondercange",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Luxembourg",
    "countryCode": "LU",
    "city": "Mondercange",
    "address": "59, Rue de Limpach, Mondercange, Canton Esch-sur-Alzette, 3932, Luxembourg",
    "lat": 49.537153,
    "lng": 5.984795,
    "websiteUrl": "https://www.acl.lu/en/leisures/karting/",
    "phone": "+352 37 90 01"
  },
  {
    "id": "30",
    "slug": "brands-hatch-circuit",
    "name": "Brands Hatch Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Sevenoaks",
    "address": "Brands Hatch Circuit, London Road, West Kingsdown, Sevenoaks, Kent, England, DA3 8NG, United Kingdom",
    "lat": 51.357488,
    "lng": 0.260006,
    "websiteUrl": "https://www.brandshatch.co.uk/",
    "phone": "+44 1474 872331"
  },
  {
    "id": "31",
    "slug": "donington-park",
    "name": "Donington Park",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Derby",
    "address": "Donington Park, Walton Hill, Castle Donington, Isley Walton, Derby, Leicestershire, England, DE74 2RP, United Kingdom",
    "lat": 52.828352,
    "lng": -1.379287,
    "websiteUrl": "https://www.donington-park.co.uk/",
    "phone": "01332 810048"
  },
  {
    "id": "32",
    "slug": "oulton-park-circuit",
    "name": "Oulton Park Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Tarporley",
    "address": "Oulton Park Circuit, Park Road, Tarporley, Cheshire West and Chester, England, CW6 9BW, United Kingdom",
    "lat": 53.180566,
    "lng": -2.614347,
    "websiteUrl": "https://www.oultonpark.co.uk/",
    "phone": "01829 760301"
  },
  {
    "id": "33",
    "slug": "snetterton-circuit",
    "name": "Snetterton Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Breckland District",
    "address": "Snetterton Motor Racing Circuit, London Road, South End, Snetterton, Breckland District, Norfolk, England, NR16 2FQ, United Kingdom",
    "lat": 52.465397,
    "lng": 0.947571,
    "websiteUrl": "https://www.snetterton.co.uk/",
    "phone": "+44 1953 887303"
  },
  {
    "id": "34",
    "slug": "cadwell-park-circuit",
    "name": "Cadwell Park Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "East Lindsey",
    "address": "The Club House, Horncastle Road, Cadwell Highfield, Tathwell, East Lindsey, Lincolnshire, Greater Lincolnshire, England, LN11 9SE, United Kingdom",
    "lat": 53.311203,
    "lng": -0.06084,
    "websiteUrl": "https://www.cadwellpark.co.uk/"
  },
  {
    "id": "35",
    "slug": "castle-combe-circuit",
    "name": "Castle Combe Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Chippenham",
    "address": "Castle Combe Circuit, Upper Castle Combe Road, Yatton Keynell, Upper Castle Combe, Chippenham, Wiltshire, England, SN14 7EY, United Kingdom",
    "lat": 51.489696,
    "lng": -2.211579,
    "websiteUrl": "https://castlecombecircuit.co.uk/"
  },
  {
    "id": "37",
    "slug": "thruxton-circuit",
    "name": "Thruxton Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Test Valley",
    "address": "Thruxton Down, Thruxton, Kimpton, Test Valley, Hampshire, England, SP11 8PN, United Kingdom",
    "lat": 51.207191,
    "lng": -1.608526,
    "websiteUrl": "https://thruxtonracing.co.uk/",
    "phone": "01264 882222"
  },
  {
    "id": "38",
    "slug": "croft-circuit",
    "name": "Croft Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Darlington",
    "address": "Croft Circuit, Secondary Paddock, Darlington, North Yorkshire, York and North Yorkshire, England, DL2 2PL, United Kingdom",
    "lat": 54.456047,
    "lng": -1.558831,
    "websiteUrl": "https://croftcircuit.co.uk/"
  },
  {
    "id": "40",
    "slug": "sim-racing-center-dusseldorf",
    "name": "Sim Racing Center Düsseldorf",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Dusseldorf",
    "address": "Classic Remise Düsseldorf, 110a, Harffstraße, Oberbilk, Stadtbezirk 3, Dusseldorf, North Rhine-Westphalia, 40591, Germany",
    "lat": 51.195028,
    "lng": 6.823599,
    "websiteUrl": "https://simracing-center.de",
    "phone": "0172 7509881"
  },
  {
    "id": "42",
    "slug": "nurburgring-esports-simracing-bar-and-lounge",
    "name": "Nürburgring eSports SimRacing Bar & Lounge",
    "categories": [
      "sim_racing",
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Nürburg",
    "address": "Haus B, 1, Otto-Flimm-Straße, Nürburg, Adenau, Landkreis Ahrweiler, Rhineland-Palatinate, 53520, Germany",
    "lat": 50.335998,
    "lng": 6.950159,
    "websiteUrl": "https://www.nuerburgring-esports.com/en/",
    "phone": "+49 2691 3029935"
  },
  {
    "id": "43",
    "slug": "apex-one-sim-racing-center",
    "name": "Apex One Sim Racing Center",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Wrocław",
    "address": "McDonald's, 95, Powstańców Śląskich, Wrocław, Lower Silesian Voivodeship, 53-332, Poland",
    "lat": 51.094861,
    "lng": 17.020387,
    "websiteUrl": "https://apexone.pl/en/"
  },
  {
    "id": "46",
    "slug": "racehall-stockholm",
    "name": "Racehall Stockholm",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Sweden",
    "countryCode": "SE",
    "city": "Södertälje",
    "address": "Racehall Stockholm AB, Sörmlandsleden, Tysslinge, Södertälje, Botkyrka kommun, Stockholm County, 144 63, Sweden",
    "lat": 59.162267,
    "lng": 17.739991,
    "websiteUrl": "https://racehall.com/en/booking-stockholm/",
    "phone": "+46 8 551 210 00"
  },
  {
    "id": "47",
    "slug": "action-house-fun-center",
    "name": "Action House Fun Center",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Denmark",
    "countryCode": "DK",
    "city": "Løkken",
    "address": "1, Industrivej, Åsendrup, Løkken, Hjørring Municipality, North Denmark Region, 9480, Denmark",
    "lat": 57.373426,
    "lng": 9.728612,
    "websiteUrl": "https://actionhouse.dk/en/go-kart/",
    "phone": "+45 99 67 67 10"
  },
  {
    "id": "48",
    "slug": "harald-huysman-karting",
    "name": "Harald Huysman Karting",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Norway",
    "countryCode": "NO",
    "city": "Oslo",
    "address": "34, Smalvollveien, Øvre Breivoll, Breivoll, Alna, Oslo, 0667, Norway",
    "lat": 59.918972,
    "lng": 10.83619,
    "websiteUrl": "https://hhk.no/",
    "phone": "+47 23 05 13 00"
  },
  {
    "id": "49",
    "slug": "kart-in-club-helsinki",
    "name": "Kart in Club Helsinki",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Finland",
    "countryCode": "FI",
    "city": "Helsinki",
    "address": "Kart in Club Helsinki, 39, Koskelantie, Kumpula, Central major district, Helsinki, Helsinki sub-region, Uusimaa, Mainland Finland, 00610, Finland",
    "lat": 60.215084,
    "lng": 24.968055,
    "websiteUrl": "https://www.kic.fi/helsinki/",
    "phone": "+358 44 776 5000"
  },
  {
    "id": "51",
    "slug": "kirkistown-motor-racing-circuit",
    "name": "Kirkistown Motor Racing Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Portavogie",
    "address": "Kirkistown Circuit, Kirkistown, Portavogie, Ards and North Down District, County Down, Northern Ireland, United Kingdom",
    "lat": 54.456945,
    "lng": -5.474835,
    "websiteUrl": "https://kirkistown.com/"
  },
  {
    "id": "52",
    "slug": "kartodromo-athens",
    "name": "Kartodromo Athens",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Greece",
    "countryCode": "GR",
    "city": "Nea Palatia",
    "address": "Γεωρ. Γεννηματά, Nea Palatia, Municipality of Oropos, Regional Unit of East Attica, Attica, 190 15, Greece",
    "lat": 38.31871,
    "lng": 23.795104,
    "websiteUrl": "https://kartodromo.gr",
    "phone": "+30 2295 023265"
  },
  {
    "id": "53",
    "slug": "racing-kart-santa-marina",
    "name": "Racing Kart Santa Marina",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Greece",
    "countryCode": "GR",
    "city": "Koropi",
    "address": "Koropi, Σπύρου Δάβαρη, Koropi, Municipality of Kropia, Regional Unit of East Attica, Attica, 194 00, Greece",
    "lat": 37.913012,
    "lng": 23.895811
  },
  {
    "id": "54",
    "slug": "athens-megara-circuit",
    "name": "Athens Megara Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Greece",
    "countryCode": "GR",
    "city": "Municipal Unit of Megara",
    "address": "Athens - Patras, Community of Megara, Municipal Unit of Megara, Municipality of Megara, Regional Unit of West Attica, Attica, 191 90, Greece",
    "lat": 37.986817,
    "lng": 23.362546,
    "websiteUrl": "http://www.athenscircuit.gr/",
    "phone": "+30 697 997 7097"
  },
  {
    "id": "57",
    "slug": "sim-racing-f1-nl",
    "name": "Sim Racing F1 NL",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Netherlands",
    "countryCode": "NL",
    "city": "IJsselstein",
    "address": "7, Edisonweg, De Corridor, IJsselstein, Utrecht, Netherlands, 3404 LA, Netherlands",
    "lat": 52.006863,
    "lng": 5.045634,
    "websiteUrl": "https://simracingf1.nl/",
    "phone": "+31 6 35118354"
  },
  {
    "id": "59",
    "slug": "a1karting-warsaw",
    "name": "A1Karting Warsaw",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Warsaw",
    "address": "A1Karting, 24B, Annopol, Żerań, Białołęka, Warsaw, Masovian Voivodeship, 03-236, Poland",
    "lat": 52.315317,
    "lng": 21.015104,
    "websiteUrl": "https://a1karting.pl",
    "phone": "+48 22 290 33 88"
  },
  {
    "id": "60",
    "slug": "racing-kart-krakow",
    "name": "Racing Kart Kraków",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Sulechów",
    "address": "27, Centralna, Cymingi, Sulechów, gmina Kocmyrzów-Luborzyca, Kraków County, Lesser Poland Voivodeship, 32-010, Poland",
    "lat": 50.128406,
    "lng": 20.096669,
    "websiteUrl": "https://www.racingkart.pl/",
    "phone": "+48 798 304 060"
  },
  {
    "id": "61",
    "slug": "s8-race",
    "name": "S8 Race",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Nadarzyn",
    "address": "68, Aleja Katowicka, Nadarzyn, gmina Nadarzyn, Pruszków County, Masovian Voivodeship, 05-830, Poland",
    "lat": 52.102073,
    "lng": 20.8228,
    "websiteUrl": "https://s8race.pl/en/home-english/",
    "phone": "+48 539 050 345"
  },
  {
    "id": "62",
    "slug": "sim-racing-center-wemmel",
    "name": "Sim Racing Center Wemmel",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Belgium",
    "countryCode": "BE",
    "city": "Wemmel",
    "address": "224, Is. Meyskensstraat - Rue Is. Meyskens, Zone C: Meyskens, Wemmel, Halle-Vilvoorde, Flemish Brabant, Flanders, 1780, Belgium",
    "lat": 50.896532,
    "lng": 4.313067,
    "websiteUrl": "https://sim-center.be/en",
    "phone": "+32 486 13 65 44"
  },
  {
    "id": "63",
    "slug": "vmax-karting-romexpo",
    "name": "VMax Karting Romexpo",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Romania",
    "countryCode": "RO",
    "city": "Bucharest",
    "address": "Bulevardul Expoziției, Domenii, Băneasa, Sector 1, Bucharest, 012101, Romania",
    "lat": 44.47744,
    "lng": 26.065797,
    "websiteUrl": "https://vmaxromexpo.ro/en/",
    "phone": "+40 760 100 855"
  },
  {
    "id": "64",
    "slug": "amckart-tunari",
    "name": "AMCKART Tunari",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Romania",
    "countryCode": "RO",
    "city": "Tunari",
    "address": "AERZEN ROMANIA, 25A, Șoseaua de Centură, Tunari, Ilfov, 077190, Romania",
    "lat": 44.530396,
    "lng": 26.156488,
    "websiteUrl": "http://www.amckart.ro/tunari/",
    "phone": "+40 741 100 700"
  },
  {
    "id": "66",
    "slug": "autodromo-do-estoril",
    "name": "Autódromo do Estoril",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Portugal",
    "countryCode": "PT",
    "city": "Cascais",
    "address": "Avenida Alfredo César Torres, Penha Longa, Alcabideche, Cascais, Lisbon, 2645-267, Portugal",
    "lat": 38.744189,
    "lng": -9.392879,
    "websiteUrl": "https://www.circuito-estoril.pt/en/"
  },
  {
    "id": "67",
    "slug": "in-and-outdoor-kartbahn-wien",
    "name": "In & Outdoor Kartbahn Wien",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Vienna",
    "address": "Robust Industry, 18, Hosnedlgasse, Katastralgemeinde Kagran, Donaustadt, Vienna, 1220, Austria",
    "lat": 48.25861,
    "lng": 16.465159,
    "websiteUrl": "https://kartbahn-wien.at",
    "phone": "0676 3217990"
  },
  {
    "id": "68",
    "slug": "speedarena-go-kart-bahn-in-rechnitz",
    "name": "Speedarena Go Kart Bahn in Rechnitz",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Rechnitz",
    "address": "29, Gewerbepark, Katastralgemeinde Rechnitz, Rechnitz, Bezirk Oberwart, Burgenland, 7471, Austria",
    "lat": 47.282294,
    "lng": 16.44375,
    "websiteUrl": "https://speedarena.at",
    "phone": "03363 79556"
  },
  {
    "id": "69",
    "slug": "karting-center-maribor",
    "name": "Karting Center Maribor",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Orehova vas",
    "address": "10, Letališka cesta, Orehova vas, Hoče-Slivnica, 2204, Slovenia",
    "lat": 46.478789,
    "lng": 15.681495,
    "websiteUrl": "https://cibikart.si",
    "phone": "+386 31 577 581"
  },
  {
    "id": "70",
    "slug": "gokart-centar-west",
    "name": "GoKart Centar West",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Town of Zaprešić",
    "address": "Frizerska oprema i pribor, 2, Zaprešićka ulica, Jablanovec, Town of Zaprešić, Zagreb County, 10298, Croatia",
    "lat": 45.871715,
    "lng": 15.826431,
    "websiteUrl": "https://gokartcentar.hr",
    "phone": "+385 99 162 6447"
  },
  {
    "id": "71",
    "slug": "pro-karting-koper",
    "name": "Pro karting Koper",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Koper / Capodistria",
    "address": "Kolodvorska cesta / Strada della Stazione, Olmo, Koper / Capodistria (naselje), Koper / Capodistria, Upravna enota Koper / Unità amministrativa Capodistria, 6000, Slovenia",
    "lat": 45.53989,
    "lng": 13.736471,
    "websiteUrl": "https://prokartingslovenija.si",
    "phone": "+386 64 117 017"
  },
  {
    "id": "72",
    "slug": "karting-koper-kartodromo-capodistria",
    "name": "Karting Koper / Kartodromo Capodistria",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Koper / Capodistria",
    "address": "Kolodvorska cesta / Strada della Stazione, Olmo, Koper / Capodistria (naselje), Koper / Capodistria, Upravna enota Koper / Unità amministrativa Capodistria, 6000, Slovenia",
    "lat": 45.53989,
    "lng": 13.736471,
    "phone": "+386 41 647 772"
  },
  {
    "id": "73",
    "slug": "ala-karting-circuit",
    "name": "Ala Karting Circuit",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Ala",
    "address": "Strada Provinciale Destra Adige, Cumerlotti, Pilcante, Ala, Comunità della Vallagarina, Provincia di Trento, Trentino – Alto Adige/Südtirol, 38061, Italy",
    "lat": 45.787178,
    "lng": 11.012046,
    "websiteUrl": "https://alakarting.it",
    "phone": "+39 366 226 3776"
  },
  {
    "id": "74",
    "slug": "spirit-karting-ag",
    "name": "Spirit Karting AG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Bremgarten",
    "address": "8, Sonnengutstrasse, Bremgarten, Bezirk Bremgarten, Aargau, 5620, Switzerland",
    "lat": 47.351062,
    "lng": 8.349244,
    "websiteUrl": "https://spirit-karting.com",
    "phone": "+41 76 435 83 55"
  },
  {
    "id": "75",
    "slug": "indoor-karting-waldshut-gmbh",
    "name": "Indoor-Karting Waldshut GmbH",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Waldshut-Tiengen",
    "address": "Kartbahn, 27, Auweg, Waldshut-Tiengen, VVG der Stadt Waldshut-Tiengen, Landkreis Waldshut, Baden-Württemberg, 79761, Germany",
    "lat": 47.613715,
    "lng": 8.18658,
    "websiteUrl": "https://kartbahn-waldshut.de",
    "phone": "+49 7751 910132"
  },
  {
    "id": "76",
    "slug": "pista-go-kart-locarno-magadino",
    "name": "Pista Go-Kart Locarno-Magadino",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Locarno",
    "address": "30, Via al Pizzante, Locarno, Circolo di Locarno, Distretto di Locarno, Ticino, 6595, Switzerland",
    "lat": 46.167957,
    "lng": 8.897006,
    "websiteUrl": "https://karts.ch",
    "phone": "+41 91 745 44 55"
  },
  {
    "id": "77",
    "slug": "kartbahn-kappelen-ag",
    "name": "Kartbahn Kappelen AG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Lyss",
    "address": "31, Lyssstrasse, Lyss, Seeland administrative district, Seeland administrative region, Bern, 3250, Switzerland",
    "lat": 47.065884,
    "lng": 7.287514,
    "websiteUrl": "https://kartbahnlyss.ch",
    "phone": "+41 32 392 22 33"
  },
  {
    "id": "78",
    "slug": "karting-payerneland",
    "name": "Karting Payerneland",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Payerne",
    "address": "Laura Park, 14, Route de Berne, Corges, Payerne, District de la Broye-Vully, Vaud, 1551, Switzerland",
    "lat": 46.813436,
    "lng": 6.953655,
    "websiteUrl": "https://payerneland.ch",
    "phone": "+41 26 660 04 60"
  },
  {
    "id": "80",
    "slug": "karting-centar-bijeljina",
    "name": "Karting Centar Bijeljina",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Bosnia and Herzegovina",
    "countryCode": "BA",
    "city": "Bijeljina",
    "address": "Robot, 79a, Pantelinska, Bijeljina, City of Bijeljina, Republika Srpska, 76300, Bosnia and Herzegovina",
    "lat": 44.74189,
    "lng": 19.191614,
    "websiteUrl": "https://karting-centar.com",
    "phone": "+387 65 636-111"
  },
  {
    "id": "81",
    "slug": "karting-arena-speedxtreme-tuzla",
    "name": "Karting Arena SpeedXtreme Tuzla",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Bosnia and Herzegovina",
    "countryCode": "BA",
    "city": "Šićki Brod",
    "address": "Industrijska, Šićki Brod, City of Tuzla, Tuzla Canton, Federation of Bosnia and Herzegovina, 75212, Bosnia and Herzegovina",
    "lat": 44.520268,
    "lng": 18.591352,
    "websiteUrl": "https://facebook.com",
    "phone": "+387 62 449 449"
  },
  {
    "id": "82",
    "slug": "speedworld-kart-racing",
    "name": "Speedworld Kart Racing",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Pachfurth",
    "address": "PaintballPark Wien - Airsoft, 1, Freizeitzentrum, Katastralgemeinde Pachfurth, Pachfurth, Rohrau, Bezirk Bruck an der Leitha, Lower Austria, 2471, Austria",
    "lat": 48.033909,
    "lng": 16.824016,
    "websiteUrl": "https://speedworld-kart.at",
    "phone": "02162 68380"
  },
  {
    "id": "83",
    "slug": "kartbahn-ziersdorf-kartshop-eichinger",
    "name": "Kartbahn Ziersdorf - Kartshop Eichinger",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Gettsdorf",
    "address": "175, An der Bundesstraße, Katastralgemeinde Großmeiseldorf, Gettsdorf, Ziersdorf, Bezirk Hollabrunn, Lower Austria, 3711, Austria",
    "lat": 48.537168,
    "lng": 15.904446,
    "websiteUrl": "https://kartbahn.cc",
    "phone": "0664 4328005"
  },
  {
    "id": "84",
    "slug": "daytona-raceways",
    "name": "Daytona Raceways",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Langenzersdorf",
    "address": "Daytona Cart Racing, 33a, Hochaustraße, Katastralgemeinde Langenzersdorf, Langenzersdorf, Bezirk Korneuburg, Lower Austria, 2103, Austria",
    "lat": 48.289526,
    "lng": 16.367177,
    "websiteUrl": "https://daytona.at",
    "phone": "02244 30560"
  },
  {
    "id": "85",
    "slug": "racb-karting-spa-francorchamps",
    "name": "RACB Karting Spa-Francorchamps",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Belgium",
    "countryCode": "BE",
    "city": "Stavelot",
    "address": "4, Route de l'Eau Rouge, Zoning de Chefosse, Amermont, Stavelot, Verviers, Liège, Wallonia, 4970, Belgium",
    "lat": 50.407807,
    "lng": 5.949643,
    "websiteUrl": "https://francorchamps-karting.be",
    "phone": "+32 87 27 58 54"
  },
  {
    "id": "86",
    "slug": "curva-del-carro-misano-world-circuit",
    "name": "Curva del Carro - Misano World Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Fano",
    "address": "Via II Strada, Bellocchi, Fano, Pesaro e Urbino, Marche, 61032, Italy",
    "lat": 43.802091,
    "lng": 12.995248
  },
  {
    "id": "87",
    "slug": "porsche-experience-center-leipzig",
    "name": "Porsche Experience Center Leipzig",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Leipzig",
    "address": "Porsche-Werk Leipzig, 1, Porschestraße, Lützschena-Stahmeln, Nordwest, Leipzig, Saxony, 04158, Germany",
    "lat": 51.406468,
    "lng": 12.290159,
    "websiteUrl": "https://porsche-leipzig.com",
    "phone": "+49 341 99913911"
  },
  {
    "id": "88",
    "slug": "prokart-raceland-gmbh-and-co-kg",
    "name": "Prokart Raceland GmbH & Co. KG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Rauberweiherhaus",
    "address": "8, Industriestraße, Rauberweiherhaus, Wackersdorf, Wackersdorf (VGem), Landkreis Schwandorf, Bavaria, 92442, Germany",
    "lat": 49.326404,
    "lng": 12.214769,
    "websiteUrl": "https://prokart-raceland.com",
    "phone": "+49 9431 75520"
  },
  {
    "id": "90",
    "slug": "steel-ring-trinec-ltd",
    "name": "STEEL RING TRINEC Ltd.",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Czechia",
    "countryCode": "CZ",
    "city": "Třinec",
    "address": "860, Staré Město, Třinec, okres Frýdek-Místek, Moravian-Silesian Region, 739 61, Czechia",
    "lat": 49.691071,
    "lng": 18.667562,
    "websiteUrl": "https://steelring.cz",
    "phone": "+420 733 738 213"
  },
  {
    "id": "91",
    "slug": "verkehrssicherheitszentrum-and-sachsenring-gmbh-and-co-kg",
    "name": "Verkehrssicherheitszentrum & Sachsenring GmbH & Co. KG",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Oberlungwitz",
    "address": "2, Am Sachsenring, Gewerbegebiet Am Sachsenring, Oberlungwitz, Zwickau, Saxony, 09353, Germany",
    "lat": 50.789835,
    "lng": 12.695784,
    "websiteUrl": "https://sachsenring.de",
    "phone": "+49 3723 65330"
  },
  {
    "id": "93",
    "slug": "raceland-krsko",
    "name": "Raceland Krško",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Pesje",
    "address": "Raceland, 30, Pesje, Krško, 8270, Slovenia",
    "lat": 45.930549,
    "lng": 15.535294
  },
  {
    "id": "94",
    "slug": "kartodrom-bura",
    "name": "Kartodrom Bura",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Šmrika",
    "address": "D501, Burići, Šmrika, Grad Kraljevica, Primorje-Gorski Kotar County, 51241, Croatia",
    "lat": 45.258347,
    "lng": 14.605336
  },
  {
    "id": "95",
    "slug": "green-garden-go-kart",
    "name": "Green Garden Go kart",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Grad Pula",
    "address": "Green Garden Go kart, 12, Šijanska cesta, Monte Šerpo, Mjesni odbor Busoler, Pula, Grad Pula, Istria County, 52100, Croatia",
    "lat": 44.881426,
    "lng": 13.870048
  },
  {
    "id": "96",
    "slug": "circuit-paddock",
    "name": "Circuit Paddock",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Spain",
    "countryCode": "ES",
    "city": "Castellolí",
    "address": "Parcmotor Castellolí, paddock, Can n'Alzina, Castellolí, Anoia, Barcelona, Catalonia, 08719, Spain",
    "lat": 41.591862,
    "lng": 1.692544
  },
  {
    "id": "97",
    "slug": "kartodromo-internacional-do-algarve",
    "name": "Kartódromo Internacional do Algarve",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Portugal",
    "countryCode": "PT",
    "city": "Portimão",
    "address": "Kartódromo Internacional do Algarve, Rua Nunes Lisa, Mexilhoeira Grande, Portimão, Faro, 8500-148, Portugal",
    "lat": 37.233274,
    "lng": -8.635789
  },
  {
    "id": "98",
    "slug": "south-garda-karting",
    "name": "South Garda Karting",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Lonato del Garda",
    "address": "Via Monti Slossaroli, Brodena, Lonato del Garda, Brescia, Lombardy, 25017, Italy",
    "lat": 45.42502,
    "lng": 10.506064
  },
  {
    "id": "99",
    "slug": "race-inn",
    "name": "Race-Inn",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Roggwil (BE)",
    "address": "50, Brunnmatt, Weibelacker, Roggwil (BE), Oberaargau administrative district, Emmental-Oberaargau administrative region, Bern, 4914, Switzerland",
    "lat": 47.247826,
    "lng": 7.807715
  },
  {
    "id": "100",
    "slug": "kart-bahn-wohlen-ag",
    "name": "Kart - Bahn - Wohlen AG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Waltenschwil",
    "address": "Gründlistrasse, Büelisacker, Waltenschwil, Bezirk Muri, Aargau, 5622, Switzerland",
    "lat": 47.326429,
    "lng": 8.297128
  },
  {
    "id": "101",
    "slug": "circuit-du-laquais",
    "name": "Circuit du Laquais",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "France",
    "countryCode": "FR",
    "city": "Champier",
    "address": "Circuit du Laquais, Chemin du Laquais, Champier, Vienne, Isère, Auvergne-Rhône-Alpes, Metropolitan France, 38260, France",
    "lat": 45.470114,
    "lng": 5.297756
  },
  {
    "id": "102",
    "slug": "vaison-piste",
    "name": "Vaison Piste",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "France",
    "countryCode": "FR",
    "city": "Torcy",
    "address": "Vaison Piste, Route des Bizots, Le Meix Augrand, Torcy, Autun, Saône-et-Loire, Bourgogne – Franche-Comté, Metropolitan France, 71210, France",
    "lat": 46.764443,
    "lng": 4.443176
  },
  {
    "id": "103",
    "slug": "circuit-de-bresse",
    "name": "Circuit de Bresse",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "France",
    "countryCode": "FR",
    "city": "Frontenaud",
    "address": "Circuit de Bresse, Route de Milleure, ZA de Milleure, L'Étang du Bief, Frontenaud, Louhans-Châteaurenaud, Saône-et-Loire, Bourgogne – Franche-Comté, Metropolitan France, 71580, France",
    "lat": 46.551272,
    "lng": 5.328889
  },
  {
    "id": "104",
    "slug": "oamtc-fahrtechnikzentrum-wachauring",
    "name": "ÖAMTC Fahrtechnikzentrum Wachauring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Melk",
    "address": "ÖAMTC Ring (Hauptgebäude), 2, Am Wachauring, Katastralgemeinde Pöverding, Pöverding, Melk, Bezirk Melk, Lower Austria, 3390, Austria",
    "lat": 48.212392,
    "lng": 15.327512
  },
  {
    "id": "105",
    "slug": "max-60",
    "name": "MAX 60",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovakia",
    "countryCode": "SK",
    "city": "Bratislava",
    "address": "Max 60, 11868/127A, Vajnorská, Dynamitka, Bratislava, District of Bratislava III, Bratislava, Borinka, Region of Bratislava, 831 02, Slovakia",
    "lat": 48.181121,
    "lng": 17.154071
  },
  {
    "id": "106",
    "slug": "kart-center-kottingbrunn",
    "name": "Kart Center Kottingbrunn",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Kottingbrunn",
    "address": "Kart Center Kottingbrunn, 4, Gewerbestraße, Katastralgemeinde Kottingbrunn, Kottingbrunn, Bezirk Baden, Lower Austria, 2542, Austria",
    "lat": 47.952182,
    "lng": 16.220232
  },
  {
    "id": "107",
    "slug": "monza",
    "name": "Monza",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Macherio",
    "address": "Via San Cassiano, Macherio, Monza and Brianza, Lombardy, 20853, Italy",
    "lat": 45.639542,
    "lng": 9.27883
  },
  {
    "id": "108",
    "slug": "styria-karting-gesmbh",
    "name": "Styria Karting GesmbH",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Forst",
    "address": "Styria Karting GesmbH, 30, Feldkirchenstraße, Thalerhof, Katastralgemeinde Kalsdorf, Forst, Kalsdorf, Bezirk Graz-Umgebung, Styria, 8401, Austria",
    "lat": 46.970281,
    "lng": 15.46252
  },
  {
    "id": "109",
    "slug": "automotodrom-grobnik",
    "name": "Automotodrom Grobnik",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Soboli",
    "address": "Motodrom Rijeka Grobnik, A6, Soboli, Općina Čavle, Primorje-Gorski Kotar County, 51219, Croatia",
    "lat": 45.382654,
    "lng": 14.50833
  },
  {
    "id": "110",
    "slug": "autodromo-enzo-e-dino-ferrari",
    "name": "Autodromo Enzo e Dino Ferrari",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Imola",
    "address": "Autodromo Internazionale Enzo e Dino Ferrari, Pista ciclabile Diego Ronchini, Centro, Imola, Nuovo Circondario Imolese, Bologna, Emilia-Romagna, 40026, Italy",
    "lat": 44.340992,
    "lng": 11.711896
  },
  {
    "id": "111",
    "slug": "mugello-circuit",
    "name": "Mugello Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Scarperia",
    "address": "15, Via dell'Autodromo, Scarperia, Scarperia e San Piero, Unione Montana dei Comuni del Mugello, Florence, Tuscany, 50038, Italy",
    "lat": 43.999382,
    "lng": 11.372365
  },
  {
    "id": "112",
    "slug": "autodromo-vallelunga-piero-taruffi",
    "name": "Autodromo Vallelunga Piero Taruffi",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Campagnano di Roma",
    "address": "Vallelunga Circuit \"Piero Taruffi\", Via Valle Grassa, Campagnano di Roma, Roma Capitale, Lazio, 00063, Italy",
    "lat": 42.160969,
    "lng": 12.369862
  },
  {
    "id": "113",
    "slug": "nurburgring",
    "name": "Nürburgring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Nürburg",
    "address": "Nürburgring, B 258, Nürburg, Adenau, Landkreis Ahrweiler, Rhineland-Palatinate, 53520, Germany",
    "lat": 50.33092,
    "lng": 6.940674
  },
  {
    "id": "114",
    "slug": "sachsenring",
    "name": "Sachsenring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Zwickau",
    "address": "Ärztehaus Zwickau, 67a, Crimmitschauer Straße, Weißenborn, Zwickau-West, Zwickau, Langenweißbach, Zwickau, Saxony, 08058, Germany",
    "lat": 50.73286,
    "lng": 12.475105
  },
  {
    "id": "115",
    "slug": "hungaroring-gokart-center",
    "name": "Hungaroring GoKart Center",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Hungary",
    "countryCode": "HU",
    "city": "Mogyoród",
    "address": "Hungarokart Gokart Center, Hungaroring út, Mogyoróska, Klastromhegy, Mogyoród, Gödöllő Regional Unit, Pest, Central Hungary, 2146, Hungary",
    "lat": 47.591051,
    "lng": 19.23996
  },
  {
    "id": "116",
    "slug": "motorsport-arena-oschersleben",
    "name": "Motorsport Arena Oschersleben",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Oschersleben",
    "address": "Motorsport Arena Oschersleben, B 246, Oschersleben, Börde, Saxony-Anhalt, 39387, Germany",
    "lat": 52.02781,
    "lng": 11.279129
  },
  {
    "id": "117",
    "slug": "red-bull-ring",
    "name": "Red Bull Ring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Flatschach",
    "address": "Red-Bull-Ring-Straße, Kattigar, Katastralgemeinde Schönberg, Flatschach, Spielberg, Bezirk Murtal, Styria, 8720, Austria",
    "lat": 47.222131,
    "lng": 14.764316
  },
  {
    "id": "118",
    "slug": "hungaroring",
    "name": "Hungaroring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Hungary",
    "countryCode": "HU",
    "city": "Mogyoród",
    "address": "Hungaroring, 10, Hungaroring út, Mogyoróska, Klastromhegy, Mogyoród, Gödöllő Regional Unit, Pest, Central Hungary, 2146, Hungary",
    "lat": 47.582649,
    "lng": 19.250024
  },
  {
    "id": "119",
    "slug": "silesia-ring-kamien-slaski",
    "name": "Silesia Ring - Kamień Śląski",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Kamień Śląski",
    "address": "Silesia Ring, Lotnicza, Kamień Śląski, gmina Gogolin, Krapkowice County, Opole Voivodeship, 47-325, Poland",
    "lat": 50.528216,
    "lng": 18.097507
  },
  {
    "id": "120",
    "slug": "pannonia-ring",
    "name": "Pannonia Ring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Hungary",
    "countryCode": "HU",
    "city": "Ostffyasszonyfa",
    "address": "Pannónia Ring, 8451, Ostffyasszonyfa, Celldömölki járás, Vas, Western Transdanubia, Transdanubia, 9512, Hungary",
    "lat": 47.306395,
    "lng": 17.038277
  },
  {
    "id": "121",
    "slug": "autodrom-most",
    "name": "AUTODROM MOST",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Czechia",
    "countryCode": "CZ",
    "city": "Most",
    "address": "Autodrom Most, Hořanská cesta, Souš, Most, okres Most, Ústí nad Labem Region, 435 02, Czechia",
    "lat": 50.51822,
    "lng": 13.597915
  },
  {
    "id": "122",
    "slug": "slovakia-ring",
    "name": "Slovakia Ring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Slovakia",
    "countryCode": "SK",
    "city": "Orechová Potôň",
    "address": "Slovakia Ring, 1435, Orechová Potôň, District of Dunajská Streda, Region of Trnava, 930 16, Slovakia",
    "lat": 48.054621,
    "lng": 17.564862
  },
  {
    "id": "123",
    "slug": "daytona-raceway",
    "name": "Daytona Raceway",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Cyprus",
    "countryCode": "CY",
    "city": "Nisou",
    "address": "Daytona raceway, Chalepianon Road - Tseriou, Nisou, South Nicosia - Dali Municipality, Nicosia District, Cyprus, 2571, Cyprus",
    "lat": 35.052582,
    "lng": 33.374948,
    "websiteUrl": "https://www.daytona.com.cy/",
    "phone": "+357 22461220"
  },
  {
    "id": "124",
    "slug": "need-4-speed-karting-centre",
    "name": "Need 4 Speed Karting Centre",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Cyprus",
    "countryCode": "CY",
    "city": "Kantou",
    "address": "Need 4 Speed Go Karting, Leoforos Troodous, Kantou, Kourio Municipality, Limassol District, Cyprus, 4631, Cyprus",
    "lat": 34.683866,
    "lng": 32.911288,
    "websiteUrl": "https://limassolkartingcentre.com/",
    "phone": "+357 99462269"
  }
];
