// Generated by data/import/import-to-db.ts — do not edit by hand.
// Re-run `npm run import:load` after updating data/import/review.csv.
import type { Listing } from "@/lib/types";

export const generatedListings: Listing[] = [
  {
    "id": "1",
    "slug": "racehall-stockholm",
    "name": "Racehall Stockholm",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Sweden",
    "countryCode": "SE",
    "city": "Södertälje",
    "address": "Racehall Stockholm AB, Sörmlandsleden, Tysslinge, Södertälje, Botkyrka kommun, Stockholm County, 144 63, Sweden",
    "lat": 59.162267,
    "lng": 17.739991,
    "websiteUrl": "https://racehall.com/en/booking-stockholm/",
    "phone": "+46 8 551 210 00"
  },
  {
    "id": "2",
    "slug": "action-house-fun-center",
    "name": "Action House Fun Center",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Denmark",
    "countryCode": "DK",
    "city": "Løkken",
    "address": "1, Industrivej, Åsendrup, Løkken, Hjørring Municipality, North Denmark Region, 9480, Denmark",
    "lat": 57.373426,
    "lng": 9.728612,
    "websiteUrl": "https://actionhouse.dk/en/go-kart/",
    "phone": "+45 99 67 67 10"
  },
  {
    "id": "3",
    "slug": "harald-huysman-karting",
    "name": "Harald Huysman Karting",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Norway",
    "countryCode": "NO",
    "city": "Oslo",
    "address": "34, Smalvollveien, Øvre Breivoll, Breivoll, Alna, Oslo, 0667, Norway",
    "lat": 59.918972,
    "lng": 10.83619,
    "websiteUrl": "https://hhk.no/",
    "phone": "+47 23 05 13 00"
  },
  {
    "id": "4",
    "slug": "kart-in-club-helsinki",
    "name": "Kart in Club Helsinki",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Finland",
    "countryCode": "FI",
    "city": "Helsinki",
    "address": "Kart in Club Helsinki, 39, Koskelantie, Kumpula, Central major district, Helsinki, Helsinki sub-region, Uusimaa, Mainland Finland, 00610, Finland",
    "lat": 60.215084,
    "lng": 24.968055,
    "websiteUrl": "https://www.kic.fi/helsinki/",
    "phone": "+358 44 776 5000"
  },
  {
    "id": "5",
    "slug": "mondello-park",
    "name": "Mondello Park",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Ireland",
    "countryCode": "IE",
    "city": "Donore",
    "address": "Mondello Park, R409, Donore, Donore ED, The Municipal District of Clane — Maynooth, County Kildare, Leinster, Ireland",
    "lat": 53.257564,
    "lng": -6.748963,
    "websiteUrl": "https://mondellopark.ie/",
    "phone": "+353 45 860200"
  },
  {
    "id": "6",
    "slug": "kirkistown-motor-racing-circuit",
    "name": "Kirkistown Motor Racing Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Portavogie",
    "address": "Kirkistown Circuit, Kirkistown, Portavogie, Ards and North Down District, County Down, Northern Ireland, United Kingdom",
    "lat": 54.456945,
    "lng": -5.474835,
    "websiteUrl": "https://kirkistown.com/"
  },
  {
    "id": "7",
    "slug": "kartodromo-athens",
    "name": "Kartodromo Athens",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Greece",
    "countryCode": "GR",
    "city": "Nea Palatia",
    "address": "Γεωρ. Γεννηματά, Nea Palatia, Municipality of Oropos, Regional Unit of East Attica, Attica, 190 15, Greece",
    "lat": 38.31871,
    "lng": 23.795104,
    "websiteUrl": "https://kartodromo.gr",
    "phone": "+30 2295 023265"
  },
  {
    "id": "8",
    "slug": "racing-kart-santa-marina",
    "name": "Racing Kart Santa Marina",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Greece",
    "countryCode": "GR",
    "city": "Koropi",
    "address": "Koropi, Σπύρου Δάβαρη, Koropi, Municipality of Kropia, Regional Unit of East Attica, Attica, 194 00, Greece",
    "lat": 37.913012,
    "lng": 23.895811
  },
  {
    "id": "9",
    "slug": "athens-megara-circuit",
    "name": "Athens Megara Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Greece",
    "countryCode": "GR",
    "city": "Municipal Unit of Megara",
    "address": "Athens - Patras, Community of Megara, Municipal Unit of Megara, Municipality of Megara, Regional Unit of West Attica, Attica, 191 90, Greece",
    "lat": 37.986817,
    "lng": 23.362546,
    "websiteUrl": "http://www.athenscircuit.gr/",
    "phone": "+30 697 997 7097"
  },
  {
    "id": "10",
    "slug": "drive-lounge-london",
    "name": "Drive Lounge London",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Greater London",
    "address": "The White Company, Ariel Way, Shepherd's Bush, London Borough of Hammersmith and Fulham, Greater London, England, W12 7NS, United Kingdom",
    "lat": 51.509114,
    "lng": -0.222012,
    "websiteUrl": "https://www.drivelounge.co.uk/locations/london/",
    "phone": "0203 307 6003"
  },
  {
    "id": "11",
    "slug": "silverstone-sim-suite",
    "name": "Silverstone Sim Suite",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "United Kingdom",
    "countryCode": "GB",
    "city": "Silverstone",
    "address": "Luffield Terrace, Lillingstone Dayrell with Luffield Abbey, Buckinghamshire, England, NN12 8GZ, United Kingdom",
    "lat": 52.07414,
    "lng": -1.021811,
    "websiteUrl": "https://www.silverstonemuseum.co.uk/whats-on/sim-suite-at-silverstone/"
  },
  {
    "id": "12",
    "slug": "sim-racing-f1-nl",
    "name": "Sim Racing F1 NL",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Netherlands",
    "countryCode": "NL",
    "city": "IJsselstein",
    "address": "7, Edisonweg, De Corridor, IJsselstein, Utrecht, Netherlands, 3404 LA, Netherlands",
    "lat": 52.006863,
    "lng": 5.045634,
    "websiteUrl": "https://simracingf1.nl/",
    "phone": "+31 6 35118354"
  },
  {
    "id": "13",
    "slug": "racesquare-rotterdam",
    "name": "Racesquare Rotterdam",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Netherlands",
    "countryCode": "NL",
    "city": "Rotterdam",
    "address": "Hollywood Café, 513, Cor Kieboomplein, De Veranda, Oud-IJsselmonde, IJsselmonde, Rotterdam, South Holland, Netherlands, 3077 MK, Netherlands",
    "lat": 51.896101,
    "lng": 4.525016,
    "websiteUrl": "https://www.racesquare.com/vestiging/rotterdam/"
  },
  {
    "id": "14",
    "slug": "a1karting-warsaw",
    "name": "A1Karting Warsaw",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Warsaw",
    "address": "A1Karting, 24B, Annopol, Żerań, Białołęka, Warsaw, Masovian Voivodeship, 03-236, Poland",
    "lat": 52.315317,
    "lng": 21.015104,
    "websiteUrl": "https://a1karting.pl",
    "phone": "+48 22 290 33 88"
  },
  {
    "id": "15",
    "slug": "racing-kart-krakow",
    "name": "Racing Kart Kraków",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Sulechów",
    "address": "27, Centralna, Cymingi, Sulechów, gmina Kocmyrzów-Luborzyca, Kraków County, Lesser Poland Voivodeship, 32-010, Poland",
    "lat": 50.128406,
    "lng": 20.096669,
    "websiteUrl": "https://www.racingkart.pl/",
    "phone": "+48 798 304 060"
  },
  {
    "id": "16",
    "slug": "s8-race",
    "name": "S8 Race",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Nadarzyn",
    "address": "68, Aleja Katowicka, Nadarzyn, gmina Nadarzyn, Pruszków County, Masovian Voivodeship, 05-830, Poland",
    "lat": 52.102073,
    "lng": 20.8228,
    "websiteUrl": "https://s8race.pl/en/home-english/",
    "phone": "+48 539 050 345"
  },
  {
    "id": "17",
    "slug": "sim-racing-center-wemmel",
    "name": "Sim Racing Center Wemmel",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Belgium",
    "countryCode": "BE",
    "city": "Wemmel",
    "address": "224, Is. Meyskensstraat - Rue Is. Meyskens, Zone C: Meyskens, Wemmel, Halle-Vilvoorde, Flemish Brabant, Flanders, 1780, Belgium",
    "lat": 50.896532,
    "lng": 4.313067,
    "websiteUrl": "https://sim-center.be/en",
    "phone": "+32 486 13 65 44"
  },
  {
    "id": "18",
    "slug": "vmax-karting-romexpo",
    "name": "VMax Karting Romexpo",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Romania",
    "countryCode": "RO",
    "city": "Bucharest",
    "address": "Bulevardul Expoziției, Domenii, Băneasa, Sector 1, Bucharest, 012101, Romania",
    "lat": 44.47744,
    "lng": 26.065797,
    "websiteUrl": "https://vmaxromexpo.ro/en/",
    "phone": "+40 760 100 855"
  },
  {
    "id": "19",
    "slug": "amckart-tunari",
    "name": "AMCKART Tunari",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Romania",
    "countryCode": "RO",
    "city": "Tunari",
    "address": "AERZEN ROMANIA, 25A, Șoseaua de Centură, Tunari, Ilfov, 077190, Romania",
    "lat": 44.530396,
    "lng": 26.156488,
    "websiteUrl": "http://www.amckart.ro/tunari/",
    "phone": "+40 741 100 700"
  },
  {
    "id": "20",
    "slug": "escuderia-madrid",
    "name": "Escudería Madrid",
    "categories": [
      "sim_racing"
    ],
    "status": "published",
    "country": "Spain",
    "countryCode": "ES",
    "city": "Las Rozas de Madrid",
    "address": "32, Avenida de Lazarejo, El Cantizal, Las Rozas de Madrid, Community of Madrid, 28232, Spain",
    "lat": 40.526288,
    "lng": -3.929606,
    "websiteUrl": "https://www.escuderiamadrid.com/",
    "phone": "+34 910 591 582"
  },
  {
    "id": "21",
    "slug": "autodromo-do-estoril",
    "name": "Autódromo do Estoril",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Portugal",
    "countryCode": "PT",
    "city": "Cascais",
    "address": "Avenida Alfredo César Torres, Penha Longa, Alcabideche, Cascais, Lisbon, 2645-267, Portugal",
    "lat": 38.744189,
    "lng": -9.392879,
    "websiteUrl": "https://www.circuito-estoril.pt/en/"
  },
  {
    "id": "22",
    "slug": "in-and-outdoor-kartbahn-wien",
    "name": "In & Outdoor Kartbahn Wien",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Vienna",
    "address": "Robust Industry, 18, Hosnedlgasse, Katastralgemeinde Kagran, Donaustadt, Vienna, 1220, Austria",
    "lat": 48.25861,
    "lng": 16.465159,
    "websiteUrl": "https://kartbahn-wien.at",
    "phone": "0676 3217990"
  },
  {
    "id": "23",
    "slug": "speedarena-go-kart-bahn-in-rechnitz",
    "name": "Speedarena Go Kart Bahn in Rechnitz",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Rechnitz",
    "address": "29, Gewerbepark, Katastralgemeinde Rechnitz, Rechnitz, Bezirk Oberwart, Burgenland, 7471, Austria",
    "lat": 47.282294,
    "lng": 16.44375,
    "websiteUrl": "https://speedarena.at",
    "phone": "03363 79556"
  },
  {
    "id": "24",
    "slug": "karting-center-maribor",
    "name": "Karting Center Maribor",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Orehova vas",
    "address": "10, Letališka cesta, Orehova vas, Hoče-Slivnica, 2204, Slovenia",
    "lat": 46.478789,
    "lng": 15.681495,
    "websiteUrl": "https://cibikart.si",
    "phone": "+386 31 577 581"
  },
  {
    "id": "25",
    "slug": "gokart-centar-west",
    "name": "GoKart Centar West",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Town of Zaprešić",
    "address": "Frizerska oprema i pribor, 2, Zaprešićka ulica, Jablanovec, Town of Zaprešić, Zagreb County, 10298, Croatia",
    "lat": 45.871715,
    "lng": 15.826431,
    "websiteUrl": "https://gokartcentar.hr",
    "phone": "+385 99 162 6447"
  },
  {
    "id": "26",
    "slug": "pro-karting-koper",
    "name": "Pro karting Koper",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Koper / Capodistria",
    "address": "Kolodvorska cesta / Strada della Stazione, Olmo, Koper / Capodistria (naselje), Koper / Capodistria, Upravna enota Koper / Unità amministrativa Capodistria, 6000, Slovenia",
    "lat": 45.540391,
    "lng": 13.736191,
    "websiteUrl": "https://prokartingslovenija.si",
    "phone": "+386 64 117 017"
  },
  {
    "id": "27",
    "slug": "karting-koper-kartodromo-capodistria",
    "name": "Karting Koper / Kartodromo Capodistria",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Koper / Capodistria",
    "address": "Kolodvorska cesta / Strada della Stazione, Olmo, Koper / Capodistria (naselje), Koper / Capodistria, Upravna enota Koper / Unità amministrativa Capodistria, 6000, Slovenia",
    "lat": 45.540391,
    "lng": 13.736191,
    "phone": "+386 41 647 772"
  },
  {
    "id": "28",
    "slug": "ala-karting-circuit",
    "name": "Ala Karting Circuit",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Ala",
    "address": "Strada Provinciale Destra Adige, Cumerlotti, Pilcante, Ala, Comunità della Vallagarina, Provincia di Trento, Trentino – Alto Adige/Südtirol, 38061, Italy",
    "lat": 45.787178,
    "lng": 11.012046,
    "websiteUrl": "https://alakarting.it",
    "phone": "+39 366 226 3776"
  },
  {
    "id": "29",
    "slug": "spirit-karting-ag",
    "name": "Spirit Karting AG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Bremgarten",
    "address": "8, Sonnengutstrasse, Bremgarten, Bezirk Bremgarten, Aargau, 5620, Switzerland",
    "lat": 47.351062,
    "lng": 8.349244,
    "websiteUrl": "https://spirit-karting.com",
    "phone": "+41 76 435 83 55"
  },
  {
    "id": "30",
    "slug": "indoor-karting-waldshut-gmbh",
    "name": "Indoor-Karting Waldshut GmbH",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Waldshut-Tiengen",
    "address": "Kartbahn, 27, Auweg, Waldshut-Tiengen, VVG der Stadt Waldshut-Tiengen, Landkreis Waldshut, Baden-Württemberg, 79761, Germany",
    "lat": 47.613715,
    "lng": 8.18658,
    "websiteUrl": "https://kartbahn-waldshut.de",
    "phone": "+49 7751 910132"
  },
  {
    "id": "31",
    "slug": "pista-go-kart-locarno-magadino",
    "name": "Pista Go-Kart Locarno-Magadino",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Locarno",
    "address": "30, Via al Pizzante, Locarno, Circolo di Locarno, Distretto di Locarno, Ticino, 6595, Switzerland",
    "lat": 46.167957,
    "lng": 8.897006,
    "websiteUrl": "https://karts.ch",
    "phone": "+41 91 745 44 55"
  },
  {
    "id": "32",
    "slug": "kartbahn-kappelen-ag",
    "name": "Kartbahn Kappelen AG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Lyss",
    "address": "31, Lyssstrasse, Lyss, Seeland administrative district, Seeland administrative region, Bern, 3250, Switzerland",
    "lat": 47.065884,
    "lng": 7.287514,
    "websiteUrl": "https://kartbahnlyss.ch",
    "phone": "+41 32 392 22 33"
  },
  {
    "id": "33",
    "slug": "karting-payerneland",
    "name": "Karting Payerneland",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Payerne",
    "address": "Laura Park, 14, Route de Berne, Corges, Payerne, District de la Broye-Vully, Vaud, 1551, Switzerland",
    "lat": 46.813436,
    "lng": 6.953655,
    "websiteUrl": "https://payerneland.ch",
    "phone": "+41 26 660 04 60"
  },
  {
    "id": "34",
    "slug": "karting-centar-bijeljina",
    "name": "Karting Centar Bijeljina",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Bosnia and Herzegovina",
    "countryCode": "BA",
    "city": "Bijeljina",
    "address": "Robot, 79a, Pantelinska, Bijeljina, City of Bijeljina, Republika Srpska, 76300, Bosnia and Herzegovina",
    "lat": 44.74189,
    "lng": 19.191614,
    "websiteUrl": "https://karting-centar.com",
    "phone": "+387 65 636-111"
  },
  {
    "id": "35",
    "slug": "karting-arena-speedxtreme-tuzla",
    "name": "Karting Arena SpeedXtreme Tuzla",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Bosnia and Herzegovina",
    "countryCode": "BA",
    "city": "Šićki Brod",
    "address": "Industrijska, Šićki Brod, City of Tuzla, Tuzla Canton, Federation of Bosnia and Herzegovina, 75212, Bosnia and Herzegovina",
    "lat": 44.521561,
    "lng": 18.599531,
    "websiteUrl": "https://facebook.com",
    "phone": "+387 62 449 449"
  },
  {
    "id": "36",
    "slug": "speedworld-kart-racing",
    "name": "Speedworld Kart Racing",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Pachfurth",
    "address": "PaintballPark Wien - Airsoft, 1, Freizeitzentrum, Katastralgemeinde Pachfurth, Pachfurth, Rohrau, Bezirk Bruck an der Leitha, Lower Austria, 2471, Austria",
    "lat": 48.033909,
    "lng": 16.824016,
    "websiteUrl": "https://speedworld-kart.at",
    "phone": "02162 68380"
  },
  {
    "id": "37",
    "slug": "kartbahn-ziersdorf-kartshop-eichinger",
    "name": "Kartbahn Ziersdorf - Kartshop Eichinger",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Gettsdorf",
    "address": "175, An der Bundesstraße, Katastralgemeinde Großmeiseldorf, Gettsdorf, Ziersdorf, Bezirk Hollabrunn, Lower Austria, 3711, Austria",
    "lat": 48.537168,
    "lng": 15.904446,
    "websiteUrl": "https://kartbahn.cc",
    "phone": "0664 4328005"
  },
  {
    "id": "38",
    "slug": "daytona-raceways",
    "name": "Daytona Raceways",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Langenzersdorf",
    "address": "Daytona Cart Racing, 33a, Hochaustraße, Katastralgemeinde Langenzersdorf, Langenzersdorf, Bezirk Korneuburg, Lower Austria, 2103, Austria",
    "lat": 48.289526,
    "lng": 16.367177,
    "websiteUrl": "https://daytona.at",
    "phone": "02244 30560"
  },
  {
    "id": "39",
    "slug": "racb-karting-spa-francorchamps",
    "name": "RACB Karting Spa-Francorchamps",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Belgium",
    "countryCode": "BE",
    "city": "Stavelot",
    "address": "Garage F. Balci, 2b, Route de l'Eau Rouge, Zoning de Chefosse, Amermont, Stavelot, Verviers, Liège, Wallonia, 4970, Belgium",
    "lat": 50.403362,
    "lng": 5.948096,
    "websiteUrl": "https://francorchamps-karting.be",
    "phone": "+32 87 27 58 54"
  },
  {
    "id": "40",
    "slug": "curva-del-carro-misano-world-circuit",
    "name": "Curva del Carro - Misano World Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Fano",
    "address": "Via II Strada, Bellocchi, Fano, Pesaro e Urbino, Marche, 61032, Italy",
    "lat": 43.802091,
    "lng": 12.995248
  },
  {
    "id": "41",
    "slug": "porsche-experience-center-leipzig",
    "name": "Porsche Experience Center Leipzig",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Leipzig",
    "address": "Porsche-Werk Leipzig, 1, Porschestraße, Güterverkehrszentrum Nord, Lützschena-Stahmeln, Nordwest, Leipzig, Saxony, 04158, Germany",
    "lat": 51.406468,
    "lng": 12.290159,
    "websiteUrl": "https://porsche-leipzig.com",
    "phone": "+49 341 99913911"
  },
  {
    "id": "42",
    "slug": "prokart-raceland-gmbh-and-co-kg",
    "name": "Prokart Raceland GmbH & Co. KG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Rauberweiherhaus",
    "address": "8, Industriestraße, Rauberweiherhaus, Wackersdorf, Wackersdorf (VGem), Landkreis Schwandorf, Bavaria, 92442, Germany",
    "lat": 49.326404,
    "lng": 12.214769,
    "websiteUrl": "https://prokart-raceland.com",
    "phone": "+49 9431 75520"
  },
  {
    "id": "43",
    "slug": "steel-ring-trinec-ltd",
    "name": "STEEL RING TRINEC Ltd.",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Czechia",
    "countryCode": "CZ",
    "city": "Třinec",
    "address": "860, Staré Město, Třinec, okres Frýdek-Místek, Moravian-Silesian Region, 739 61, Czechia",
    "lat": 49.691071,
    "lng": 18.667562,
    "websiteUrl": "https://steelring.cz",
    "phone": "+420 733 738 213"
  },
  {
    "id": "44",
    "slug": "verkehrssicherheitszentrum-and-sachsenring-gmbh-and-co-kg",
    "name": "Verkehrssicherheitszentrum & Sachsenring GmbH & Co. KG",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Oberlungwitz",
    "address": "2, Am Sachsenring, Gewerbegebiet Am Sachsenring, Oberlungwitz, Zwickau, Saxony, 09353, Germany",
    "lat": 50.789835,
    "lng": 12.695784,
    "websiteUrl": "https://sachsenring.de",
    "phone": "+49 3723 65330"
  },
  {
    "id": "45",
    "slug": "amazinga",
    "name": "Amazinga",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "City of Zagreb",
    "address": "Amazinga, Ulica Józsefa Antalla, Mjesni odbor Kajzerica, Gradska četvrt Novi Zagreb - zapad, Zagreb, City of Zagreb, 10160, Croatia",
    "lat": 45.782717,
    "lng": 15.975576
  },
  {
    "id": "46",
    "slug": "raceland-krsko",
    "name": "Raceland Krško",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovenia",
    "countryCode": "SI",
    "city": "Pesje",
    "address": "Raceland, 30, Pesje, Krško, 8270, Slovenia",
    "lat": 45.930549,
    "lng": 15.535294
  },
  {
    "id": "47",
    "slug": "kartodrom-bura",
    "name": "Kartodrom Bura",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Šmrika",
    "address": "D501, Burići, Šmrika, Grad Kraljevica, Primorje-Gorski Kotar County, 51241, Croatia",
    "lat": 45.258347,
    "lng": 14.605336
  },
  {
    "id": "48",
    "slug": "green-garden-go-kart",
    "name": "Green Garden Go kart",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Grad Pula",
    "address": "Green Garden Go kart, 12, Šijanska cesta, Monte Šerpo, Mjesni odbor Busoler, Pula, Grad Pula, Istria County, 52100, Croatia",
    "lat": 44.881426,
    "lng": 13.870048
  },
  {
    "id": "49",
    "slug": "circuit-paddock",
    "name": "Circuit Paddock",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Spain",
    "countryCode": "ES",
    "city": "Castellolí",
    "address": "Parcmotor Castellolí, paddock, Can n'Alzina, Castellolí, Anoia, Barcelona, Catalonia, 08719, Spain",
    "lat": 41.591862,
    "lng": 1.692544
  },
  {
    "id": "50",
    "slug": "kartodromo-internacional-do-algarve",
    "name": "Kartódromo Internacional do Algarve",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Portugal",
    "countryCode": "PT",
    "city": "Portimão",
    "address": "Kartódromo Internacional do Algarve, Rua Nunes Lisa, Mexilhoeira Grande, Portimão, Faro, 8500-148, Portugal",
    "lat": 37.233274,
    "lng": -8.635789
  },
  {
    "id": "51",
    "slug": "south-garda-karting",
    "name": "South Garda Karting",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Lonato del Garda",
    "address": "Via Monti Slossaroli, Brodena, Lonato del Garda, Brescia, Lombardy, 25017, Italy",
    "lat": 45.42502,
    "lng": 10.506064
  },
  {
    "id": "52",
    "slug": "race-inn",
    "name": "Race-Inn",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Roggwil (BE)",
    "address": "50, Brunnmatt, Weibelacker, Roggwil (BE), Oberaargau administrative district, Emmental-Oberaargau administrative region, Bern, 4914, Switzerland",
    "lat": 47.247826,
    "lng": 7.807715
  },
  {
    "id": "53",
    "slug": "kart-bahn-wohlen-ag",
    "name": "Kart - Bahn - Wohlen AG",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Switzerland",
    "countryCode": "CH",
    "city": "Waltenschwil",
    "address": "Gründlistrasse, Büelisacker, Waltenschwil, Bezirk Muri, Aargau, 5622, Switzerland",
    "lat": 47.326429,
    "lng": 8.297128
  },
  {
    "id": "54",
    "slug": "circuit-du-laquais",
    "name": "Circuit du Laquais",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "France",
    "countryCode": "FR",
    "city": "Champier",
    "address": "Circuit du Laquais, Chemin du Laquais, Champier, Vienne, Isère, Auvergne-Rhône-Alpes, Metropolitan France, 38260, France",
    "lat": 45.470114,
    "lng": 5.297756
  },
  {
    "id": "55",
    "slug": "vaison-piste",
    "name": "Vaison Piste",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "France",
    "countryCode": "FR",
    "city": "Torcy",
    "address": "Vaison Piste, Route des Bizots, Le Meix Augrand, Torcy, Autun, Saône-et-Loire, Bourgogne – Franche-Comté, Metropolitan France, 71210, France",
    "lat": 46.764443,
    "lng": 4.443176
  },
  {
    "id": "56",
    "slug": "circuit-de-bresse",
    "name": "Circuit de Bresse",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "France",
    "countryCode": "FR",
    "city": "Frontenaud",
    "address": "Circuit de Bresse, Autoroute Verte, L'Étang du Bief, Frontenaud, Louhans-Châteaurenaud, Saône-et-Loire, Bourgogne – Franche-Comté, Metropolitan France, 71580, France",
    "lat": 46.551272,
    "lng": 5.328889
  },
  {
    "id": "57",
    "slug": "oamtc-fahrtechnikzentrum-wachauring",
    "name": "ÖAMTC Fahrtechnikzentrum Wachauring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Melk",
    "address": "ÖAMTC Ring (Hauptgebäude), 2, Am Wachauring, Katastralgemeinde Pöverding, Pöverding, Melk, Bezirk Melk, Lower Austria, 3390, Austria",
    "lat": 48.212392,
    "lng": 15.327512
  },
  {
    "id": "58",
    "slug": "max-60",
    "name": "MAX 60",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Slovakia",
    "countryCode": "SK",
    "city": "Bratislava",
    "address": "Max 60, 11868/127A, Vajnorská, Dynamitka, Bratislava, District of Bratislava III, Bratislava, Borinka, Region of Bratislava, 831 02, Slovakia",
    "lat": 48.181121,
    "lng": 17.154071
  },
  {
    "id": "59",
    "slug": "kart-center-kottingbrunn",
    "name": "Kart Center Kottingbrunn",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Kottingbrunn",
    "address": "Kart Center Kottingbrunn, 4, Gewerbestraße, Katastralgemeinde Kottingbrunn, Kottingbrunn, Bezirk Baden, Lower Austria, 2542, Austria",
    "lat": 47.952182,
    "lng": 16.220232
  },
  {
    "id": "60",
    "slug": "monza",
    "name": "Monza",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Macherio",
    "address": "Via San Cassiano, Macherio, Monza and Brianza, Lombardy, 20853, Italy",
    "lat": 45.639542,
    "lng": 9.27883
  },
  {
    "id": "61",
    "slug": "styria-karting-gesmbh",
    "name": "Styria Karting GesmbH",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Forst",
    "address": "Styria Karting GesmbH, 30, Feldkirchenstraße, Thalerhof, Katastralgemeinde Kalsdorf, Forst, Kalsdorf, Bezirk Graz-Umgebung, Styria, 8401, Austria",
    "lat": 46.970281,
    "lng": 15.46252
  },
  {
    "id": "62",
    "slug": "automotodrom-grobnik",
    "name": "Automotodrom Grobnik",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Croatia",
    "countryCode": "HR",
    "city": "Soboli",
    "address": "Motodrom Rijeka Grobnik, A6, Soboli, Općina Čavle, Primorje-Gorski Kotar County, 51219, Croatia",
    "lat": 45.382654,
    "lng": 14.50833
  },
  {
    "id": "63",
    "slug": "autodromo-enzo-e-dino-ferrari",
    "name": "Autodromo Enzo e Dino Ferrari",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Imola",
    "address": "Autodromo Internazionale Enzo e Dino Ferrari, Via Tazio Nuvolari, Caranta, Tre Monti - Zello, Imola, Nuovo Circondario Imolese, Bologna, Emilia-Romagna, 40026, Italy",
    "lat": 44.340992,
    "lng": 11.711896
  },
  {
    "id": "64",
    "slug": "mugello-circuit",
    "name": "Mugello Circuit",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Scarperia",
    "address": "15, Via dell'Autodromo, Scarperia, Scarperia e San Piero, Unione Montana dei Comuni del Mugello, Florence, Tuscany, 50038, Italy",
    "lat": 43.999382,
    "lng": 11.372365
  },
  {
    "id": "65",
    "slug": "autodromo-vallelunga-piero-taruffi",
    "name": "Autodromo Vallelunga Piero Taruffi",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Italy",
    "countryCode": "IT",
    "city": "Campagnano di Roma",
    "address": "Vallelunga Circuit \"Piero Taruffi\", Via Valle Grassa, Campagnano di Roma, Roma Capitale, Lazio, 00063, Italy",
    "lat": 42.160969,
    "lng": 12.369862
  },
  {
    "id": "66",
    "slug": "nurburgring",
    "name": "Nürburgring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Nürburg",
    "address": "Nürburgring, Müllenbacher Straße, Nürburg, Adenau, Landkreis Ahrweiler, Rhineland-Palatinate, 53520, Germany",
    "lat": 50.33092,
    "lng": 6.940674
  },
  {
    "id": "67",
    "slug": "sachsenring",
    "name": "Sachsenring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Zwickau",
    "address": "Ärztehaus Zwickau, 67a, Crimmitschauer Straße, Weißenborn, Zwickau-West, Zwickau, Langenweißbach, Zwickau, Saxony, 08058, Germany",
    "lat": 50.73286,
    "lng": 12.475105
  },
  {
    "id": "68",
    "slug": "hungaroring-gokart-center",
    "name": "Hungaroring GoKart Center",
    "categories": [
      "karting"
    ],
    "status": "published",
    "country": "Hungary",
    "countryCode": "HU",
    "city": "Mogyoród",
    "address": "Hungarokart Gokart Center, Hungaroring út, Mogyoróska, Klastromhegy, Mogyoród, Gödöllő Regional Unit, Pest, Central Hungary, 2146, Hungary",
    "lat": 47.591051,
    "lng": 19.23996
  },
  {
    "id": "69",
    "slug": "motorsport-arena-oschersleben",
    "name": "Motorsport Arena Oschersleben",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Germany",
    "countryCode": "DE",
    "city": "Oschersleben",
    "address": "Motorsport Arena Oschersleben, B 246, Oschersleben, Börde, Saxony-Anhalt, 39387, Germany",
    "lat": 52.02781,
    "lng": 11.279129
  },
  {
    "id": "70",
    "slug": "red-bull-ring",
    "name": "Red Bull Ring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Austria",
    "countryCode": "AT",
    "city": "Flatschach",
    "address": "Red-Bull-Ring-Straße, Kattigar, Katastralgemeinde Schönberg, Flatschach, Spielberg, Bezirk Murtal, Styria, 8720, Austria",
    "lat": 47.222131,
    "lng": 14.764316
  },
  {
    "id": "71",
    "slug": "hungaroring",
    "name": "Hungaroring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Hungary",
    "countryCode": "HU",
    "city": "Mogyoród",
    "address": "Hungaroring, 10, Hungaroring út, Mogyoróska, Klastromhegy, Mogyoród, Gödöllő Regional Unit, Pest, Central Hungary, 2146, Hungary",
    "lat": 47.582649,
    "lng": 19.250024
  },
  {
    "id": "72",
    "slug": "silesia-ring-kamien-slaski",
    "name": "Silesia Ring - Kamień Śląski",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Poland",
    "countryCode": "PL",
    "city": "Kamień Śląski",
    "address": "Silesia Ring, 7, Lotnicza, Kamień Śląski, gmina Gogolin, Krapkowice County, Opole Voivodeship, 47-325, Poland",
    "lat": 50.528119,
    "lng": 18.094218
  },
  {
    "id": "73",
    "slug": "pannonia-ring",
    "name": "Pannonia Ring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Hungary",
    "countryCode": "HU",
    "city": "Ostffyasszonyfa",
    "address": "Pannónia Ring, 8451, Ostffyasszonyfa, Celldömölki járás, Vas, Western Transdanubia, Transdanubia, 9512, Hungary",
    "lat": 47.306395,
    "lng": 17.038277
  },
  {
    "id": "74",
    "slug": "autodrom-most",
    "name": "AUTODROM MOST",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Czechia",
    "countryCode": "CZ",
    "city": "Most",
    "address": "Autodrom Most, Podlesí, Komořany, Most, okres Most, Ústí nad Labem Region, 434 03, Czechia",
    "lat": 50.51822,
    "lng": 13.597915
  },
  {
    "id": "75",
    "slug": "slovakia-ring",
    "name": "Slovakia Ring",
    "categories": [
      "track_day"
    ],
    "status": "published",
    "country": "Slovakia",
    "countryCode": "SK",
    "city": "Orechová Potôň",
    "address": "Slovakia Ring, 1435, Orechová Potôň, District of Dunajská Streda, Region of Trnava, 930 16, Slovakia",
    "lat": 48.054621,
    "lng": 17.564862
  }
];
