// GENERATED by data/import/sync-photo-credits.ts from data/import/cover-images.csv
// — don't edit by hand; edit the CSV and re-run `npm run import:sync-credits`.
import type { PhotoCredit } from "@/lib/types";

export const PHOTO_CREDITS: Record<string, PhotoCredit> = {
  "shanghai-international-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Shanghai_International_Circuit%2C_April_7%2C_2018_SkySat_%28rotated%29.jpg",
    "author": "Planet Labs, Inc.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shanghai_International_Circuit,_April_7,_2018_SkySat_(rotated).jpg"
  },
  "miami-international-autodrome": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Start_of_the_Porsche_Sprint_Challenge_North_America_at_the_F1_Miami_GP_-_2022.jpg",
    "author": "USACJack",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Start_of_the_Porsche_Sprint_Challenge_North_America_at_the_F1_Miami_GP_-_2022.jpg"
  },
  "circuit-de-monaco": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Circuit_de_Monaco_-_Chicane_du_port_%2854783713474%29.jpg",
    "author": "crash71100",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit_de_Monaco_-_Chicane_du_port_(54783713474).jpg"
  },
  "circuit-de-barcelona-catalunya": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Circuit_de_Barcelona-Catalunya%2C_April_19%2C_2018_SkySat_%28cropped%29.jpg",
    "author": "Planet Labs, Inc.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit_de_Barcelona-Catalunya,_April_19,_2018_SkySat_(cropped).jpg"
  },
  "circuit-gilles-villeneuve": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Circuit_Gilles_Villeneuve_NAPA_200.JPG",
    "author": "Tsunami330",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit_Gilles_Villeneuve_NAPA_200.JPG"
  },
  "circuit-de-spa-francorchamps": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a8/2022_4_Hours_of_Spa-Francorchamps_-_Circuit.jpg",
    "author": "United Autosports",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2022_4_Hours_of_Spa-Francorchamps_-_Circuit.jpg"
  },
  "circuit-zandvoort": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/55/Aerial_view_of_Motorsport_race_track_Circuit_Zandvoort_Formula_one_%2840889997713%29.jpg",
    "author": "dronepicr",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Motorsport_race_track_Circuit_Zandvoort_Formula_one_(40889997713).jpg"
  },
  "autodromo-nazionale-monza": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/65/Monza_aerial_photo.jpg",
    "license": "Copyrighted free use",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Monza_aerial_photo.jpg"
  },
  "baku-city-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Baku_City_Circuit%2C_April_9%2C_2018_SkySat.jpg",
    "author": "Planet Labs, Inc.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Baku_City_Circuit,_April_9,_2018_SkySat.jpg"
  },
  "marina-bay-street-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Singapore_%28SG%29%2C_Marina_Bay_Street_Circuit%2C_F1_Pit_Building_--_2019_--_4478.jpg",
    "author": "Dietmar Rabich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_(SG),_Marina_Bay_Street_Circuit,_F1_Pit_Building_--_2019_--_4478.jpg"
  },
  "circuit-of-the-americas": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/21/Circuit_of_the_Americas_aerial_view_from_WN4430.jpg",
    "author": "Spheroidite",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit_of_the_Americas_aerial_view_from_WN4430.jpg"
  },
  "autodromo-hermanos-rodriguez": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Vista_a%C3%A9rea_del_Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez_02.jpg",
    "author": "ProtoplasmaKid",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vista_a%C3%A9rea_del_Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez_02.jpg"
  },
  "autodromo-jose-carlos-pace": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/70/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace%2C_July_3%2C_2018_SkySat_%28cropped%29.jpg",
    "author": "Planet Labs, Inc.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace,_July_3,_2018_SkySat_(cropped).jpg"
  },
  "las-vegas-strip-circuit": {
    "imageUrl": "https://assets.simpleviewcms.com/simpleview/image/upload/c_fill,f_jpg,h_452,q_65,w_640/v1/clients/lasvegas/pit_building_2023_strip1_52d6ce82-34bc-467c-a7b1-3edcd0589d71.jpg",
    "sourceUrl": "https://www.visitlasvegas.com/f1-las-vegas-grand-prix/"
  },
  "yas-marina-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f6/North_Grandstand_at_the_Yas_Marina_circuit_in_Abu_Dhabi.jpg",
    "author": "TravelPhotosNL",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:North_Grandstand_at_the_Yas_Marina_circuit_in_Abu_Dhabi.jpg"
  },
  "brands-hatch-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/08/Brands-hatch.jpg",
    "author": "Whiters",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brands-hatch.jpg"
  },
  "donington-park": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Airliner_over_Donington_Circuit_-_geograph.org.uk_-_1222575.jpg",
    "author": "John Goldsmith",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Airliner_over_Donington_Circuit_-_geograph.org.uk_-_1222575.jpg"
  },
  "oulton-park-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/28/From_Old_Hall_Corner%2C_Oulton_Park_-_geograph.org.uk_-_5110822.jpg",
    "author": "Brian Deegan",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:From_Old_Hall_Corner,_Oulton_Park_-_geograph.org.uk_-_5110822.jpg"
  },
  "snetterton-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/df/Snetterton_Racing_Circuit_%289096594820%29.jpg",
    "author": "John Fielding from Norwich, UK",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Snetterton_Racing_Circuit_(9096594820).jpg"
  },
  "cadwell-park-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/dd/The_Mountain%2C_Cadwell_Park_-_geograph.org.uk_-_439661.jpg",
    "author": "E Gammie",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Mountain,_Cadwell_Park_-_geograph.org.uk_-_439661.jpg"
  },
  "castle-combe-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Castle_Combe_Circuit_MMB_G5.jpg",
    "author": "mattbuck (category)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Castle_Combe_Circuit_MMB_G5.jpg"
  },
  "thruxton-circuit": {
    "imageUrl": "https://tx-web-imgproxy.azureedge.net/k8OmhPUzJ0ZzgP3Vu6iu54oqTEffjJbljEkEVquNrds/w:352/h:198/rt:auto/el:1/ex:1/YWJzOi8vdGhydXh0b24vbWlzYy90aHJ1eHRvbl8yMDE2X2FfMTczLmpwZw.jpg",
    "sourceUrl": "https://thruxtonracing.co.uk/"
  },
  "croft-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/81/Croft_Circuit_%2C_North_Yorkshire_-_geograph.org.uk_-_137696.jpg",
    "author": "Hugh Mortimer",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Croft_Circuit_,_North_Yorkshire_-_geograph.org.uk_-_137696.jpg"
  },
  "laitse-rallypark-go-kart-track": {
    "imageUrl": "https://laitserallypark.ee/wp-content/uploads/2023/05/foto-036-1770x994-copy.jpg",
    "sourceUrl": "https://laitserallypark.ee/en/services/karting/"
  },
  "motorcity-karting-arena": {
    "imageUrl": "https://visitestonia.com/images/750969/motorcity-karting-arena-010-visit-estonia.png",
    "sourceUrl": "https://visitestonia.com/en/motorcity-karting-arena"
  },
  "action-house-fun-center": {
    "imageUrl": "https://actionhouse.dk/wp-content/uploads/2026/03/action-sjov-mini-turbo-gokart.jpg",
    "sourceUrl": "https://actionhouse.dk/en/go-kart/"
  },
  "harald-huysman-karting": {
    "imageUrl": "https://hhk.no/wp-content/uploads/2023/11/Huysman-karting_BAW_13-1024x683.jpg",
    "sourceUrl": "https://hhk.no/"
  },
  "kirkistown-motor-racing-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Kirkistown_Motor_Racing_Circuit_-_geograph.org.uk_-_1093480.jpg",
    "author": "David Crozier",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kirkistown_Motor_Racing_Circuit_-_geograph.org.uk_-_1093480.jpg"
  },
  "racing-kart-krakow": {
    "imageUrl": "https://www.racingkart.pl/wp-content/uploads/2021/04/MG_6629.jpeg",
    "sourceUrl": "https://www.racingkart.pl/"
  },
  "s8-race": {
    "imageUrl": "https://s8race.pl/wp-content/uploads/2025/08/IMG_4557-3-1-1024x683.jpg",
    "sourceUrl": "https://s8race.pl/en/home-english/"
  },
  "speedarena-go-kart-bahn-in-rechnitz": {
    "imageUrl": "https://speedarena.at/upload/resized/xel00880_resized_Oehyr89JgM.jpg",
    "sourceUrl": "https://speedarena.at"
  },
  "autodromo-do-estoril": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/48/Circuito_do_Estoril_%2839813638364%29.jpg",
    "author": "pedrik",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuito_do_Estoril_(39813638364).jpg"
  },
  "pista-go-kart-locarno-magadino": {
    "imageUrl": "https://www.karts.ch/wp-content/uploads/2022/10/FDA80F6E-BD15-42FF-A1D1-ECA663E5B7AE-1200x746.jpg",
    "sourceUrl": "https://karts.ch"
  },
  "karting-payerneland": {
    "imageUrl": "https://payerneland.ch/wp-content/uploads/2025/03/home-banner-indoor-mobile.jpg",
    "sourceUrl": "https://payerneland.ch"
  },
  "jeddah-corniche-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/dc/Jeddah_Corniche_Circuit_viewed_from_above.png",
    "author": "GéoFr11",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jeddah_Corniche_Circuit_viewed_from_above.png"
  },
  "nurburgring": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Porsche_996_GT3_RS_at_the_N%C3%BCrburgring_Nordschleife_Br%C3%BCnnchen.JPG",
    "author": "Agtlaw",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Porsche_996_GT3_RS_at_the_N%C3%BCrburgring_Nordschleife_Br%C3%BCnnchen.JPG"
  },
  "red-bull-ring": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/80/United_Autosports_ELMS_Red_Bull_Ring_2017-218.jpg",
    "author": "United Autosports",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:United_Autosports_ELMS_Red_Bull_Ring_2017-218.jpg"
  },
  "hungaroring": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Hungaroring%2C_Mogyor%C3%B3d_12.jpg",
    "author": "Ank Kumar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hungaroring,_Mogyor%C3%B3d_12.jpg"
  },
  "sachsenring": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/40/Aerial_image_of_Sachsenring_%28view_from_the_southwest%29.jpg",
    "author": "Carsten Steger",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_Sachsenring_(view_from_the_southwest).jpg"
  },
  "mugello-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/87/Mugello_circuit_superbike_21_September_2019_race_seen_from_the_Palagio_entrance.jpg",
    "author": "Anna.Massini",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mugello_circuit_superbike_21_September_2019_race_seen_from_the_Palagio_entrance.jpg"
  },
  "autodromo-enzo-e-dino-ferrari": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/43/Autodromo_Internazionale_Enzo_e_Dino_Ferrari_Imola.jpg",
    "author": "Monia Mascagni",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Autodromo_Internazionale_Enzo_e_Dino_Ferrari_Imola.jpg"
  },
  "autodromo-vallelunga-piero-taruffi": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/12/Vallelunga.race.circuit.in.italy.arp.jpg",
    "author": "Adrian Pingstone (Arpingstone)",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vallelunga.race.circuit.in.italy.arp.jpg"
  },
  "automotodrom-grobnik": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Automotodrom_Rijeka3.JPG",
    "author": "Pigpanter at German Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Automotodrom_Rijeka3.JPG"
  },
  "motorsport-arena-oschersleben": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Aerial_image_of_Motorsport_Arena_Oschersleben_%28view_from_the_west%29.jpg",
    "author": "Carsten Steger",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_Motorsport_Arena_Oschersleben_(view_from_the_west).jpg"
  },
  "autodrom-most": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Most_autodrom.JPG",
    "author": "Hadonos",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Most_autodrom.JPG"
  },
  "slovakia-ring": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/46/Slovakia_Ring_2018.jpg",
    "author": "Gabrysia 123",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Slovakia_Ring_2018.jpg"
  },
  "silesia-ring-kamien-slaski": {
    "imageUrl": "https://silesiaring.pl/wp-content/uploads/2026/03/SILESIA_RING_f_Dominik_Kalamus_0091-1024x682.jpg",
    "sourceUrl": "https://silesiaring.pl/"
  },
  "pannonia-ring": {
    "imageUrl": "https://pannonia-ring.com/media/2026/03/Pannonia_Ring_Turn_5.jpg",
    "sourceUrl": "https://pannonia-ring.com/en/"
  },
  "porsche-experience-center-leipzig": {
    "imageUrl": "https://www.porsche-leipzig.com/fileadmin/_processed_content/3/3/csm_Porsche-Experience-Center-Leipzig-Hero_57ef75919e.jpg",
    "sourceUrl": "https://porsche-leipzig.com"
  },
  "steel-ring-trinec-ltd": {
    "imageUrl": "https://www.steelring.cz/content_data/slider/1/1_dji-fly-20250810-094218-0091-1754811922521-photo.jpg",
    "sourceUrl": "https://www.steelring.cz/en/"
  },
  "curva-del-carro-misano-world-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Misano_World_Circuit_Marco_Simoncelli.jpg",
    "author": "Toni Pecoraro",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Misano_World_Circuit_Marco_Simoncelli.jpg"
  },
  "nemuno-ziedas-nemunas-ring": {
    "imageUrl": "https://www.lscentras.lt/images/bazes/ziedas/Nemuno_ziedas_RemoteMediaFile_6553964_0_2021_06_03_16_04_58.jpg",
    "sourceUrl": "https://lscentras.lt"
  },
  "autokomerc-karting-centar": {
    "imageUrl": "https://kart.rs/wp-content/uploads/2025/10/IMG_9567.jpg",
    "sourceUrl": "https://kart.rs/"
  },
  "kartlandas-vilnius": {
    "imageUrl": "https://www.98.lt/files/styles/wide/public/kartlandas_vilnius_atidarymas_7.jpg?itok=h7N21Ac1",
    "sourceUrl": "https://www.98.lt/kartlandas-vilnius-atidarytas"
  },
  "sofia-karting-ring": {
    "imageUrl": "https://www.sofiakarting.com/wp-content/uploads/2017/04/10608424_1008233605859163_982355582389894351_o.png",
    "sourceUrl": "https://www.sofiakarting.com/en/"
  },
  "krasna-polyana-karting": {
    "imageUrl": "https://visitsofia.bg/images/vegas_media/category30000/object3115/10a28d268f02e0646ab3c344362d7b40.jpg",
    "sourceUrl": "https://visitsofia.bg/en/cityinfrastructure/what-to-do/karting/krasna-polyana-karting-track"
  },
  "karting-mondercange": {
    "imageUrl": "https://cms.acl.lu/thumbor/dAAktfp393LSGQPnfnEYmjigMkA=/fit-in/1024x/filters:quality(92)/--/uploads/2024/04/DSC0012-3-e1713188151850.jpg",
    "sourceUrl": "https://www.acl.lu/en/leisures/karting/"
  },
  "speedworld-kart-racing": {
    "imageUrl": "https://speedworld-kart.at/images/strecke-hero.jpg",
    "sourceUrl": "https://speedworld-kart.at"
  },
  "daytona-raceway": {
    "imageUrl": "https://static.wixstatic.com/media/2cff17_54381f983ca24f41a4121295ab4fbba6~mv2.jpg/v1/fill/w_980,h_735,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/2cff17_54381f983ca24f41a4121295ab4fbba6~mv2.jpg",
    "sourceUrl": "https://www.daytona.com.cy/"
  },
  "circuit-paddock": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/17/Parcmotor_Castellol%C3%AD_09_Karting_and_Supermotard_circuit.jpg",
    "author": "Jordiferrer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parcmotor_Castellol%C3%AD_09_Karting_and_Supermotard_circuit.jpg"
  },
  "circuit-du-laquais": {
    "imageUrl": "https://circuitdulaquais.com/img/stage-pilotage-circuit-du-laquais.jpg"
  },
  "oamtc-fahrtechnikzentrum-wachauring": {
    "imageUrl": "https://www.wachauring.at/files/freiesfahren/img/jpg/Roland2.jpg"
  },
  "turbomax-karting-center": {
    "imageUrl": "https://turbomax.rs/wp-content/uploads/2025/11/karting-trka.jpg"
  },
  "sim-racing-f1-nl": {
    "imageUrl": "https://simracingf1.nl/storage/2024/07/WhatsApp-Image-2024-07-15-at-18.01.48-5-300x200.jpeg"
  },
  "skaj-kart": {
    "imageUrl": "https://skajkart.mk/wp-content/uploads/2019/10/DSC_0590.jpg"
  },
  "pro-karting-koper": {
    "imageUrl": "https://prokartingslovenija.si/wp-content/uploads/2024/07/IMG_7683.jpg"
  },
  "vmax-karting-romexpo": {
    "imageUrl": "https://vmaxromexpo.ro/wp-content/uploads/2024/02/Sesiuni-VMAX-1.jpg"
  },
  "amckart-tunari": {
    "imageUrl": "https://www.amckart.ro/assets/carusel-reel/reel-1.webp"
  },
  "indoor-karting-waldshut-gmbh": {
    "imageUrl": "https://www.kartbahn-waldshut.de/fileadmin/_processed_/1/f/csm_IMG_0119_4dafda2ef5.jpg"
  },
  "racb-karting-spa-francorchamps": {
    "imageUrl": "https://www.francorchamps-karting.be/images/site/2024121754_1734447294se.jpg"
  },
  "nurburgring-esports-simracing-bar-and-lounge": {
    "imageUrl": "https://www.nuerburgring-esports.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OTA1OTAsInB1ciI6ImJsb2JfaWQifX0=--9194c1f08c981ace07b75d137baf7891ec0c9071/Nurburgring%20Esports%20Nurburgring%20Bar%202.jpg?locale=en",
    "sourceUrl": "https://www.nuerburgring-esports.com/en/sim_racing_lounges/nurburgring-esport-bar"
  },
  "sim-racing-center-wemmel": {
    "imageUrl": "https://sim-center.be/cdn/shop/files/SIMBELGIUM-20231125-111.jpg?v=1761870651&width=3840"
  },
  "karting-koper-kartodromo-capodistria": {
    "imageUrl": "https://prokartingslovenija.si/wp-content/uploads/2024/07/IMG_7674.jpg",
    "sourceUrl": "https://prokartingslovenija.si/prokarting-koper/"
  },
  "daytona-raceways": {
    "imageUrl": "https://karthalle.wien/wp-content/uploads/2024/10/halle.jpg",
    "sourceUrl": "https://karthalle.wien/"
  },
  "kartodrom-bura": {
    "imageUrl": "https://gokartcrocup.com/ieNews/media/7-staza-bura.jpg",
    "sourceUrl": "https://gokartcrocup.com/hr/kartodrom-bura-smrika/8/"
  },
  "kart-bahn-wohlen-ag": {
    "imageUrl": "https://www.kartbahnwohlen.ch/wp-content/uploads/2022/10/kartbahn-img1.jpg"
  },
  "max-60": {
    "imageUrl": "https://www.motokary.sk/upload/banner/3.jpg",
    "sourceUrl": "https://www.motokary.sk/home?j=2"
  },
  "kart-center-kottingbrunn": {
    "imageUrl": "https://www.kartcenter.at/images/astroid_template_zero/kopfbild.png"
  },
  "vaison-piste": {
    "imageUrl": "https://www.cascadevents.fr/img/cms/Circuit/circuit-vaison.jpg",
    "sourceUrl": "https://www.cascadevents.fr/circuit-de-pilotage/bourgogne-franche-comte/vaison/"
  },
  "need-4-speed-karting-centre": {
    "imageUrl": "https://img1.wsimg.com/isteam/ip/f7cd0e1d-ad80-42ed-8b84-2374eb6e9af1/DSC_0154.jpg"
  },
  "styria-karting-gesmbh": {
    "imageUrl": "https://styriakarting.at/s3/d/wsw.website.12865/public/images/pages/kart-nordschleife-4.webp",
    "sourceUrl": "https://styriakarting.at/outdoor"
  },
  "hungaroring-gokart-center": {
    "imageUrl": "https://hungaroringkartcenter.hu/pickezdo/dsc06035_89.jpg"
  },
  "south-garda-karting": {
    "imageUrl": "https://www.lonatoturismo.it/public/photo/4aa.jpg",
    "sourceUrl": "https://www.lonatoturismo.it/it/sport-natura-spiagge/south-garda-karting"
  },
  "race-inn": {
    "imageUrl": "https://image.jimcdn.com/app/cms/image/transf/dimension=2048x2048:format=jpg/path/s9a6bbcc09155d36b/image/i1fb1e5588f502e6b/version/1551955501/image.jpg",
    "sourceUrl": "https://www.race-inn.ch/galerie/"
  },
  "gokart-centar-west": {
    "imageUrl": "https://content.selectbox.hr/uploads/2024/07/449953776_122185699022019376_1326310712170900414_n-1024x683.jpg",
    "sourceUrl": "https://www.selectbox.hr/place/gokart-centar-west/"
  },
  "kartbahn-kappelen-ag": {
    "imageUrl": "https://pcdn1.i-web.ch/KM0fIpJY2S-HNjCyRcsKbALq3m4=/600x0/smart/filters:strip_exif()/g377/0/0/63a18c86f4117",
    "sourceUrl": "https://www.kappelen.ch/sehenswuerdigkeiten/27715"
  },
  "tt-circuit-assen": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5f/TT_Circuit_Assen_grandstand.jpg",
    "author": "Michiel Jelijs",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TT_Circuit_Assen_grandstand.jpg"
  },
  "rudskogen-motorsenter": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Rudskogen2018_pr_27.jpg",
    "author": "Micke Fransson, Teambild",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rudskogen2018_pr_27.jpg"
  },
  "lydden-hill-race-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b3/View_of_Chessons_Drift_on_Lydden_circuit_race_track.jpg",
    "author": "Nick Smith",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_Chessons_Drift_on_Lydden_circuit_race_track.jpg"
  },
  "circuit-du-val-de-vienne": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Alfa_Romeo_-_Circuit_du_Val_de_Vienne_-_15-11-2014_-_Image_Picture_Photography_-_Organisateur_-_Club_AGC86_Vienne_-_www.agc86.fr_%2815800171041%29.jpg",
    "author": "Grand Parc - Bordeaux, France from France",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alfa_Romeo_-_Circuit_du_Val_de_Vienne_-_15-11-2014_-_Image_Picture_Photography_-_Organisateur_-_Club_AGC86_Vienne_-_www.agc86.fr_(15800171041).jpg"
  },
  "circuit-pau-arnos": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Circuit_Pau-Arnos_-_Le_9_f%C3%A9vrier_2014_%2812430035013%29.jpg",
    "author": "Grand Parc - Bordeaux, France from France",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit_Pau-Arnos_-_Le_9_f%C3%A9vrier_2014_(12430035013).jpg"
  },
  "circuito-ascari": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Vista_a%C3%A9rea_del_Circuito_Ascari_en_Ronda.jpg",
    "author": "Ascari Race Resort",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vista_a%C3%A9rea_del_Circuito_Ascari_en_Ronda.jpg"
  },
  "pista-azzurra-jesolo": {
    "imageUrl": "https://pista-azzurra.com/images/home/hero.jpg",
    "sourceUrl": "https://pista-azzurra.com/en"
  },
  "karting-sevilla": {
    "imageUrl": "https://www.kartingsevilla.com/wp-content/uploads/2026/04/DJI_20260424195013_0147_D-webp-1-1024x768.webp",
    "sourceUrl": "https://www.kartingsevilla.com/"
  },
  "michael-schumacher-kart-and-event-center": {
    "imageUrl": "https://www.ms-kartcenter.de/fileadmin/_processed_/5/6/csm_MS_Kartcenter_Luftaufnahme_798118ede9.webp",
    "sourceUrl": "https://www.ms-kartcenter.de"
  },
  "circuit-andorra-pas-de-la-casa": {
    "imageUrl": "https://www.circuit-andorra.com/wp-content/uploads/2022/12/slide-paginia-inici-circuit-andorra-pas-de-la-casa.jpg",
    "sourceUrl": "https://www.circuit-andorra.com"
  },
  "bilster-berg-drive-resort": {
    "imageUrl": "https://www.bilster-berg.de/wp-content/uploads/08_strecke_rennstrecke_mausefalle-mit-fahrzeugen_2017_09_04.jpg",
    "sourceUrl": "https://www.bilster-berg.de/en/services/track-day/"
  },
  "karting-des-fagnes": {
    "imageUrl": "https://i0.wp.com/kartingdesfagnes.be/wp-content/uploads/2021/05/karting-des-fagnes-vue-panoramique.jpg?resize=1200%2C441",
    "sourceUrl": "https://kartingdesfagnes.be/en/"
  },
  "a15-karting": {
    "imageUrl": "https://a15karting.nl/wp-content/uploads/2013/09/kartenhome.jpg",
    "sourceUrl": "https://a15karting.nl/"
  },
  "planet-play-velocity-track": {
    "imageUrl": "https://planetplay.com.mt/wp-content/uploads/2026/09/790756330_122297936264178827_1616168866562069930_n-1024x433.jpg",
    "sourceUrl": "https://planetplay.com.mt/race/"
  },
  "kartmax-prague": {
    "imageUrl": "https://www.kartmax.cz/gallery/karting1.jpg",
    "sourceUrl": "https://www.kartmax.cz/"
  },
  "green-garden-go-kart": {
    "imageUrl": "https://www.karting.hr/images/objects/02.jpg",
    "sourceUrl": "https://www.karting.hr/"
  },
  "verkehrssicherheitszentrum-and-sachsenring-gmbh-and-co-kg": {
    "imageUrl": "https://hohenstein-ernstthal.de/fileadmin/user_upload/Bilder/sachsenring/VSZ_Fahrsicherheitstraining.jpg",
    "sourceUrl": "https://hohenstein-ernstthal.de/sachsenring/fahrsicherheitszentrum/"
  },
  "spirit-karting-ag": {
    "imageUrl": "https://spirit-karting.ch/wp-content/uploads/2023/08/SK_101-1920x1093.jpg",
    "sourceUrl": "https://spirit-karting.ch/de/spirit-racing-de/"
  },
  "adac-nordbayern-simracing-center-weiden": {
    "imageUrl": "https://www.adac-simracing-center.de/fileadmin/_processed_/2/3/csm_58_-_ADAC_x_Thomas_Scheck_Photography_Weiden-47_3dd77e38ac.jpg"
  },
  "kart-palast-funpark": {
    "imageUrl": "https://images.prismic.io/teamsport/ZlcMwKWtHYXtT467_DE-Karting-Kart-Palast-Normal-Karting-119.png"
  },
  "anderstorp-raceway": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/80/Jessica_STCC_Audi.jpg",
    "author": "Photo: STCC",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jessica_STCC_Audi.jpg"
  },
  "raceland-krsko": {
    "imageUrl": "https://karting.raceland.si/wp-content/uploads/2022/07/raceland-glava-slika-2019-700x441.jpg"
  },
  "experience-factory-eupen": {
    "imageUrl": "https://static.experience-factory.com/eupen/wp-content/uploads/thumb-scaled-1200x800.jpg"
  },
  "e-motion-sim-racing-luxembourg": {
    "imageUrl": "https://luxembourg.e-motion.racing/images/site/are-you-ready-to-race.jpg"
  },
  "circuit-de-lignieres": {
    "imageUrl": "https://cdn.prod.website-files.com/63775f982c8a5c18c3173882/63bfc7c2709362730ad5115c_TCS_Circuit_de_Lignieres_Hero_Bild_01_Tiny.jpg"
  },
  "karting-genk": {
    "imageUrl": "https://www.kartinggenk.be/assets/images/pictures/section_section/c_c/700x450/sprint-cup-web-cover_1770622141.png"
  },
  "adventure-park-at-kartworld-cork": {
    "imageUrl": "https://adventurepark.ie/wp-content/uploads/2026/01/karting.jpg"
  },
  "arena-karting-albania": {
    "imageUrl": "https://www.pgkart.com/wp-content/uploads/2022/10/DJI_0001-2-1.jpg",
    "sourceUrl": "https://www.pgkart.com/en/works/arena-karting-albania/"
  },
  "hyperactive-prishtina-mall": {
    "imageUrl": "https://360karting.com/wp-content/uploads/2024/02/360-Karting_HyperActive-Prishtina-Mall-4.jpg",
    "sourceUrl": "https://360karting.com/project/hyperactive-prishtina-mall/"
  },
  "karting-rimo-ohrid": {
    "imageUrl": "https://images.kart-map.com/cdn-cgi/imagedelivery/v8gf-r_fKlpWuSL8cx_Jpw/circuits/karting-rimo-8465/hero169",
    "sourceUrl": "https://www.kart-map.com/en/circuits/karting-rimo"
  },
  "karting-centar-bijeljina": {
    "imageUrl": "https://op.bhrt.ba/wp-content/uploads/2020/06/karting-naslovna-1-768x294.jpg",
    "sourceUrl": "https://op.bhrt.ba/u-bijeljini-otvoren-karting-centar/"
  },
  "karting-centar-motodrom-kula": {
    "imageUrl": "https://media-cdn.tripadvisor.com/media/photo-f/10/e0/69/4e/karting-centar-motodrom.jpg",
    "sourceUrl": "https://www.tripadvisor.co.nz/LocationPhotoDirectLink-g2462753-d12275764-i283142478-Karting_centar_Motodrom_Kula-Vrbas_Vojvodina.html"
  },
  "parnu-go-karting-center": {
    "imageUrl": "https://visitestonia.com/images/3854911/F61DDF6E-BE10-4670-AB27-2B1210D7397D.jpeg",
    "sourceUrl": "https://visitestonia.com/en/parnu-go-karting-center-summer-track"
  },
  "kartingslv": {
    "imageUrl": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/d3/a0/1f/track-view-from-balcony.jpg?w=700&h=400&s=1",
    "sourceUrl": "https://www.tripadvisor.com/Attraction_Review-g274967-d28013001-Reviews-Karting_Hall_Kartings_lv-Riga_Riga_Region.html"
  },
  "bikernieku-kartinga-halle": {
    "imageUrl": "https://cdn.davanuserviss.lv/storage/photos/products/116402/38152.jpg",
    "sourceUrl": "https://www.davanuserviss.lv/davana/brauciens-ar-lielo-kartingu-bikernieku-kartinga-halle/"
  },
  "kandavas-kartodroms": {
    "imageUrl": "https://viss.lv/dati/swedbank-kartodroms/v/aai_6531.jpg",
    "sourceUrl": "https://visitkandava.lv/en/what_to_do/kandavas_kartodroms"
  },
  "kartlandas-kaunas": {
    "imageUrl": "https://assets.bookitnow.lt/files/uploaded/shops/7399cd0431b9456fa04e1ae13a5d9182.jpeg",
    "sourceUrl": "https://www.bookitnow.lt/kartlandas"
  },
  "smartkart-kyiv": {
    "imageUrl": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/08/70/06/photo0jpg.jpg?w=700&h=400&s=1",
    "sourceUrl": "https://www.tripadvisor.com/Attraction_Review-g294474-d10692218-Reviews-Karting_Center_SmartKart_Kyiv-Kyiv.html"
  },
  "chayka-karting": {
    "imageUrl": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/c0/52/89/getlstd-property-photo.jpg?w=600&h=400&s=1",
    "sourceUrl": "https://www.tripadvisor.com/Attraction_Review-g12158342-d20007936-Reviews-Chayka_Karting-Chaiky_Kiev_Oblast.html"
  },
  "formula-kart-moldova": {
    "imageUrl": "https://www.fest.md/files/places/3/image_393_8_large.jpg",
    "sourceUrl": "https://www.fest.md/en/places/sports/karting/formula-kart"
  },
  "karting-arena-speedxtreme-tuzla": {
    "imageUrl": "https://gdjeizaci.ba/wp-content/uploads/2023/07/speedxtreme-tuzla-1.jpg",
    "sourceUrl": "https://gdjeizaci.ba/rezultat/karting-arena-speedxtreme/"
  },
  "speedxtreme-karting-arena-sarajevo": {
    "imageUrl": "https://storage.radiosarajevo.ba/article/247903/871x540/kartingarenasarajevo_FB.jpg?v1481970679",
    "sourceUrl": "https://radiosarajevo.ba/auto-moto/auto-moto-zanimljivosti/adrenalinski-uzitak-sarajevo-dobilo-najvecu-indoor-karting-arenu/247903"
  },
  "lange-karting-centre": {
    "imageUrl": "https://visitestonia.com/images/743633/lange-motokeskus-013-visit-estonia.JPG",
    "sourceUrl": "https://visitestonia.com/en/lange-motokeskus"
  },
  "sim-racing-center-dusseldorf": {
    "imageUrl": "https://simracing-center.de/wp-content/uploads/simracing-fahrzeug-foto.png"
  },
  "le-mans-karting-international": {
    "imageUrl": "https://media-cdn.tripadvisor.com/media/photo-s/0e/bb/84/b4/le-mans-karting-international.jpg",
    "sourceUrl": "https://www.tripadvisor.fr/LocationPhotoDirectLink-g187195-d8504623-i247170228-Karting_des_24_Heures_du_Mans-Le_Mans_City_Le_Mans_Sarthe_Pays_de_la_Loi.html"
  },
  "pallas-karting": {
    "imageUrl": "https://media-cdn.tripadvisor.com/media/photo-f/0f/29/c0/3d/beginners-track-tynagh.jpg",
    "sourceUrl": "https://www.tripadvisor.com/LocationPhotoDirectLink-g211935-d1440102-i254394429-Pallas_Karting-Loughrea_County_Galway_Western_Ireland.html"
  },
  "kart-legend-san-marino": {
    "imageUrl": "https://media-cdn.tripadvisor.com/media/photo-f/04/78/43/27/kart-legend.jpg",
    "sourceUrl": "https://www.tripadvisor.com/LocationPhotoDirectLink-g14044169-d2266359-i74990375-Kart_Legend-Rovereta_Serravalle.html"
  },
  "circuito-tazio-nuvolari": {
    "imageUrl": "https://www.circuitotazionuvolari.it/wp-content/uploads/2025/06/XMC_4717-scaled.jpg"
  },
  "pista-winner": {
    "imageUrl": "https://www.pistawinner.it/wp-content/uploads/2023/03/pista-winner-pista-da-kart-torino.jpg"
  },
  "autodromo-del-levante": {
    "imageUrl": "https://www.levantecircuit.com/wp-content/uploads/2021/04/circuito.jpg"
  },
  "drive-park-circuit-thessaloniki": {
    "imageUrl": "https://media-cdn.tripadvisor.com/media/photo-f/14/fe/a8/a0/k-2-race-track-overview.jpg",
    "sourceUrl": "https://www.tripadvisor.com/LocationPhotoDirectLink-g12941665-d15088061-i352233632-Drive_Park-Neo_Rysio_Thessaloniki_Region_Central_Macedonia.html"
  },
  "gokartcentralen-goteborg": {
    "imageUrl": "https://gokartcentralen.se/wp-content/uploads/2020/03/Amplifyphoto__Z4A9900-768x512.jpg"
  },
  "gokartcity-malmo": {
    "imageUrl": "https://static.wixstatic.com/media/828c6c_6e1a103d32c547f1ae9a635b782cf192~mv2.jpg"
  },
  "bergen-gokartsenter": {
    "imageUrl": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/60/12/2c/caption.jpg",
    "sourceUrl": "https://www.tripadvisor.com/Attraction_Review-g2348013-d20871334-Reviews-Bergen_Gokartsenter-Straume_Fjell_Municipality_Hordaland_Western_Norway.html"
  },
  "vandel-gokart": {
    "imageUrl": "https://files.guidedanmark.org/files/410/72020_Bane.jpg",
    "sourceUrl": "https://www.destinationtrekantomraadet.com/destination-trekantomraadet/plan-your-trip/vandel-gokart-drive-on-denmarks-coolest-track-close-to-billund-gdk680000"
  },
  "kartodrom-bydgoszcz": {
    "imageUrl": "https://kartodrom.bydgoszcz.pl/wp-content/uploads/2025/05/opis-toru-Kartodrom-Bydgoszcz-768x431.webp"
  },
  "pitlane-wroclaw": {
    "imageUrl": "https://www.gokartywroclaw.pl/wp-content/uploads/2025/01/pitlane_wroclavia.jpg"
  },
  "flashkart-budapest": {
    "imageUrl": "https://gokartbudapest.hu/wp-content/uploads/2025/03/PIC_elektromos_gokart_verseny_5b.jpg"
  },
  "varna-karting-track": {
    "imageUrl": "https://www.varnakarting.com/wp-content/uploads/2019/04/Varna_Website_03.jpg"
  },
  "karting-centar-podgorica": {
    "imageUrl": "https://www.karting.me/files/slideshow/1432205983-KSP_606_0745.JPG"
  },
  "racing-kart-santa-marina": {
    "imageUrl": "https://static.wixstatic.com/media/dc74f3_a289f4955ce94783b7ee42da40b77a5c~mv2.jpg"
  },
  "coral-bay-karting-center": {
    "imageUrl": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/bf/14/2a/caption.jpg",
    "sourceUrl": "https://www.tripadvisor.com/Attraction_Review-g12616337-d18453075-Reviews-Coral_Bay_Karting_Ltd-Coral_Bay_Peyia_Paphos_District.html"
  },
  "silverstone-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Silverstone_Circuit%2C_July_2%2C_2018_SkySat_%28cropped%29.jpg",
    "author": "Planet Labs, Inc.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Silverstone_Circuit,_July_2,_2018_SkySat_(cropped).jpg"
  },
  "bahrain-international-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/26/Bahrain-International-Circuit-curve-19-vip-tower.JPG",
    "author": "Sjrake",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bahrain-International-Circuit-curve-19-vip-tower.JPG"
  },
  "albert-park-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Albert_Park_%26_Australia_Grand_Prix_Circuit.jpg",
    "author": "Donaldytong",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albert_Park_&_Australia_Grand_Prix_Circuit.jpg"
  },
  "suzuka-international-racing-course": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Suzuka_Circuit_2006.jpg",
    "author": "Shiraga",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Suzuka_Circuit_2006.jpg"
  },
  "losail-international-circuit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Grand_Stand.JPG",
    "author": "Trinidade",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grand_Stand.JPG"
  }
};
